app_handle_name = "robo_pilot"
app_screen_name = "RoboPilot"
app_screen_name_ja = "ロボ操縦"
default_window_mode = "window"
default_window_width = 172
default_window_height = 220
default_window_pos_x = 250
default_window_pos_y = 16
launcher_visible = true
