#!/usr/bin/env ruby
# Generate the FmrbConst Ruby module the Spinel kernel needs, from the C source
# of truth (headers + const.c), so the values never drift from the mruby build.
#
# The mruby build gets FmrbConst from picoruby-fmrb-const (const.c) at runtime.
# The Spinel build has no mruby C-extension layer, so we emit a plain Ruby module
# with the SAME values. Only the subset the kernel VM uses is generated (the
# desktop-only THEME_*/KEY_*/PROC_STATE_* live in the desktop port, Phase 4).
#
# Usage: ruby tool/spinel/gen_const_rb.rb <out.rb> [platform]
#   platform defaults to "linux".

require "fileutils"

ROOT = File.expand_path("../..", File.dirname(__FILE__))
out_path = ARGV[0] or abort "usage: gen_const_rb.rb <out.rb> [platform]"
platform = ARGV[1] || "linux"

def slurp(rel)
  path = File.join(ROOT, rel)
  File.exist?(path) ? File.read(path) : (abort "missing #{rel}")
end

# Parse a C enum body, honoring `NAME = value` and auto-increment. Returns a
# Hash{name => integer} for the requested names.
def enum_values(src, enum_marker, names)
  # find the enum block containing enum_marker
  idx = src.index(enum_marker) or abort "enum marker #{enum_marker} not found"
  open = src.rindex("{", idx) or abort "enum open brace not found for #{enum_marker}"
  close = src.index("}", open) or abort "enum close brace not found"
  body = src[open + 1...close]
  vals = {}
  cur = 0
  body.split(",").each do |ent|
    ent = ent.sub(%r{/\*.*?\*/}m, "").sub(%r{//.*$}, "").strip
    next if ent.empty?
    if ent =~ /\A(\w+)\s*=\s*(-?\d+)\z/
      cur = Integer($2)
      vals[$1] = cur
    elsif ent =~ /\A(\w+)\z/
      vals[$1] = cur
    end
    cur += 1
  end
  names.each_with_object({}) { |n, h| h[n] = (vals[n] or abort "enum value #{n} not found") }
end

# Parse `#define NAME value` integers.
def define_values(src, names)
  names.each_with_object({}) do |n, h|
    if src =~ /^\s*#define\s+#{Regexp.escape(n)}\s+(\S+)/
      h[n] = Integer($1, 10) rescue Integer($1)
    else
      abort "#define #{n} not found"
    end
  end
end

msg = slurp("components/fmrb_msg/fmrb_msg.h")
task = slurp("components/fmrb_common/include/fmrb_task_config.h")
led = slurp("main/drivers/led_status/status_led.h")

msg_types = enum_values(msg, "FMRB_MSG_TYPE_APP_CONTROL",
                        %w[FMRB_MSG_TYPE_APP_CONTROL FMRB_MSG_TYPE_APP_GFX
                           FMRB_MSG_TYPE_APP_AUDIO FMRB_MSG_TYPE_HID_EVENT])
proc_ids = enum_values(task, "PROC_ID_KERNEL", %w[PROC_ID_KERNEL PROC_ID_HOST])
led_vals = define_values(led, %w[FMRB_LED_STATUS_VERSION_MISMATCH])

chip_model = platform == "linux" ? "linux" : "ESP32-S3"

out = +"# AUTO-GENERATED by tool/spinel/gen_const_rb.rb -- do not edit.\n"
out << "# FmrbConst subset used by the Spinel kernel VM (values from C headers).\n"
out << "module FmrbConst\n"
out << "  PLATFORM = #{platform.inspect}\n"
out << "  CHIP_MODEL = #{chip_model.inspect}\n"
out << "  MSG_TYPE_APP_CONTROL = #{msg_types['FMRB_MSG_TYPE_APP_CONTROL']}\n"
out << "  MSG_TYPE_APP_GFX = #{msg_types['FMRB_MSG_TYPE_APP_GFX']}\n"
out << "  MSG_TYPE_APP_AUDIO = #{msg_types['FMRB_MSG_TYPE_APP_AUDIO']}\n"
out << "  MSG_TYPE_HID_EVENT = #{msg_types['FMRB_MSG_TYPE_HID_EVENT']}\n"
out << "  PROC_ID_KERNEL = #{proc_ids['PROC_ID_KERNEL']}\n"
out << "  PROC_ID_HOST = #{proc_ids['PROC_ID_HOST']}\n"
out << "  LED_ERR_VERSION_MISMATCH = #{led_vals['FMRB_LED_STATUS_VERSION_MISMATCH']}\n"
out << "end\n"

FileUtils.mkdir_p(File.dirname(out_path))
File.write(out_path, out)
warn "Wrote #{out_path} (platform=#{platform})"
