app_handle_name = "fail_app"
app_screen_name = "CompileErr"
default_window_mode = "window"

default_window_width = 50
default_window_height = 50

default_window_pos_x = 20
default_window_pos_y = 20

launcher_visible = false
