app_handle_name = "encoder8"
app_screen_name = "8Encoder"
app_screen_name_ja = "エンコーダ"
default_window_mode = "window"
default_window_width = 200
default_window_height = 100
default_window_pos_x = 10
default_window_pos_y = 20
launcher_visible = false
