app_handle_name = "require_test"
app_screen_name = "ReqTest"
default_window_mode = "window"
default_window_width = 160
default_window_height = 60
default_window_pos_x = 20
default_window_pos_y = 30
launcher_visible = false
