app_handle_name = "pysound"
app_screen_name = "PySound"
app_screen_name_ja = "Python音"
default_window_mode = "window"
default_window_width = 150
default_window_height = 120
default_window_pos_x = 80
default_window_pos_y = 60
