app_handle_name = "python"
app_screen_name = "Python demo"
app_screen_name_ja = "Pythonデモ"
default_window_mode = "window"
default_window_width = 230
default_window_height = 175
default_window_pos_x = 45
default_window_pos_y = 30
