# Family mruby Modern - ESP32-P4 (M5Stack Tab5 equivalent: 16MB flash, 32MB PSRAM)
#
# NOTE: ESP32-P4 has NO built-in radio. Wireless is provided by an ESP32-C6
# coprocessor over SDIO (like Tab5). BLE runs as host-only NimBLE on the P4
# with the controller on the C6 via esp_hosted vHCI (see the Bluetooth /
# esp_hosted sections below and doc/ble_c6_web_console.md).
#
# This file gets the build system wired for esp32p4; values still need tuning
# with menuconfig against real hardware (PSRAM speed, partition layout, etc.).

# Performance
CONFIG_FREERTOS_HZ=1000

# Log timestamp: system time (HH:MM:SS.mmm) instead of boot milliseconds
CONFIG_LOG_TIMESTAMP_SOURCE_SYSTEM=y
CONFIG_OPTIMIZATION_LEVEL_RELEASE=y

CONFIG_LOG_DEFAULT_LEVEL_INFO=y
CONFIG_LOG_MAXIMUM_LEVEL_DEBUG=y

# ESP32-P4 HP core frequency
CONFIG_ESP_DEFAULT_CPU_FREQ_MHZ_360=y
CONFIG_ESP_DEFAULT_CPU_FREQ_MHZ=360

# Partition
CONFIG_PARTITION_TABLE_CUSTOM=y
CONFIG_PARTITION_TABLE_CUSTOM_FILENAME="config/partitions_p4.csv"
CONFIG_PARTITION_TABLE_FILENAME="config/partitions_p4.csv"

# for task info
CONFIG_FREERTOS_THREAD_LOCAL_STORAGE_POINTERS=2

# --- Bluetooth: host-only NimBLE, controller on ESP32-C6 via esp_hosted vHCI ---
CONFIG_BT_ENABLED=y
CONFIG_BT_CONTROLLER_DISABLED=y
CONFIG_BT_NIMBLE_ENABLED=y
# UART HCI transport must be off: esp_hosted's vHCI option
# (ESP_HOSTED_ENABLE_BT_NIMBLE) depends on !BT_NIMBLE_TRANSPORT_UART
CONFIG_BT_NIMBLE_TRANSPORT_UART=n
CONFIG_BT_NIMBLE_SVC_GAP_DEVICE_NAME="FamilyMruby"
CONFIG_BT_NIMBLE_MAX_CONNECTIONS=1
CONFIG_BT_NIMBLE_ROLE_CENTRAL=n
CONFIG_BT_NIMBLE_ROLE_OBSERVER=n
CONFIG_BT_NIMBLE_NVS_PERSIST=y
CONFIG_BT_NIMBLE_ATT_PREFERRED_MTU=512

# --- esp_hosted: SDIO transport to ESP32-C6 (Tab5 wiring, from M5Tab5-UserDemo) ---
CONFIG_ESP_HOSTED_SDIO_HOST_INTERFACE=y
CONFIG_ESP_HOSTED_SDIO_4_BIT_BUS=y
CONFIG_ESP_HOSTED_SDIO_CLOCK_FREQ_KHZ=40000
CONFIG_ESP_HOSTED_SDIO_PIN_CMD=13
CONFIG_ESP_HOSTED_SDIO_PIN_CLK=12
CONFIG_ESP_HOSTED_SDIO_PIN_D0=11
# D1 is a derived symbol; the user-configurable one is the PRIV_ variant
CONFIG_ESP_HOSTED_SDIO_PRIV_PIN_D1_4BIT_BUS=10
CONFIG_ESP_HOSTED_SDIO_PIN_D2=9
CONFIG_ESP_HOSTED_SDIO_PIN_D3=8
CONFIG_ESP_HOSTED_SDIO_OPTIMIZATION_RX_STREAMING_MODE=y
CONFIG_ESP_HOSTED_SDIO_GPIO_RESET_SLAVE=15
CONFIG_ESP_HOSTED_SDIO_RESET_ACTIVE_LOW=y

# --- esp_hosted: Bluetooth over hosted transport (vHCI) ---
CONFIG_ESP_HOSTED_ENABLE_BT_NIMBLE=y
CONFIG_ESP_HOSTED_NIMBLE_HCI_VHCI=y

# --- esp_wifi_remote: slave target selection (read by esp_hosted 1.4.0) ---
CONFIG_SLAVE_IDF_TARGET_ESP32C6=y
CONFIG_ESP_WIFI_REMOTE_LIBRARY_HOSTED=y

# SPI-RAM (Tab5: 32MB PSRAM on ESP32-P4)
# Tab5 uses 16-line (HEX) PSRAM at 200MHz; M5GFX/the DSI framebuffer require
# 200MHz. SPIRAM_SPEED_200M depends on IDF_EXPERIMENTAL_FEATURES.
CONFIG_IDF_EXPERIMENTAL_FEATURES=y
CONFIG_SPIRAM=y
CONFIG_SPIRAM_MODE_HEX=y
CONFIG_SPIRAM_SPEED_200M=y
CONFIG_SPIRAM_USE_CAPS_ALLOC=y
# CONFIG_SPIRAM_USE_MALLOC is not set
# for large static global mem
CONFIG_SPIRAM_ALLOW_BSS_SEG_EXTERNAL_MEMORY=y

# Flash (16MB)
CONFIG_ESPTOOLPY_FLASHMODE="qio"
CONFIG_ESPTOOLPY_FLASHMODE_QIO=y
CONFIG_ESPTOOLPY_FLASHFREQ_80M=y
CONFIG_ESPTOOLPY_FLASHSIZE="16MB"
CONFIG_ESPTOOLPY_FLASHSIZE_16MB=y

CONFIG_PM_ENABLE=n

# Performance optimizations
CONFIG_COMPILER_OPTIMIZATION_PERF=y
CONFIG_COMPILER_OPTIMIZATION_ASSERTIONS_DISABLE=y

# Logging configuration
CONFIG_LOG_DEFAULT_LEVEL_INFO=y
CONFIG_LOG_DEFAULT_LEVEL=3

# FreeRTOS
CONFIG_FREERTOS_IDLE_TASK_STACKSIZE=1024
CONFIG_FREERTOS_WATCHPOINT_END_OF_STACK=y
CONFIG_FREERTOS_USE_TICKLESS_IDLE=n

# Task Watchdog: stop monitoring IDLE tasks (see Retro config rationale).
CONFIG_ESP_TASK_WDT_CHECK_IDLE_TASK_CPU0=n
CONFIG_ESP_TASK_WDT_CHECK_IDLE_TASK_CPU1=n

# SPI driver optimizations for real-time performance
CONFIG_SPI_MASTER_ISR_IN_IRAM=y
CONFIG_SPI_SLAVE_ISR_IN_IRAM=y

# USB Hub Support
CONFIG_USB_HOST_HUBS_SUPPORTED=y

# Avoid LittleFS Crash in app task
CONFIG_LITTLEFS_MALLOC_STRATEGY_DEFAULT=n
CONFIG_LITTLEFS_MALLOC_STRATEGY_INTERNAL=y
