system_name = "Family mruby OS"
display_width = 320
display_height = 240
display_margin_x = 2
display_margin_y = 16
default_user_app_width = 280
default_user_app_height = 180
display_mode = "ntsc_ipc" # spi_XXXX, etc...
debug_mode = true
mouse_scale_x = 0.5
mouse_scale_y = 0.5
timezone = "JST-9"

[theme]
desktop_bg = 0xF6
menu_bg = 0xC5
window_bg = 0xFF
text = 0x00
text_light = 0xFF
highlight = 0xC5
border = 0x60
button = 0x60
dir_color = 0x03

[[shortcuts]]
key = "l"
app = "launcher"

[[shortcuts]]
key = "s"
app = "default/shell"

[[shortcuts]]
key = "e"
app = "default/editor"

[[shortcuts]]
key = "n"
app = "app/demo/nsf_player.app.rb"

[[sync_files]]
src = "/usr/share/sounds/test.nsf"
dest = "/flash/data/test.nsf"
