#!/usr/bin/env ruby
# Time the BASIC benchmarks on a running system and report statements/second.
#
# The benchmarks (components/basic/test/samples/bench_*.bas) print a start and
# an end marker; this reads them back out of the log with their timestamps, so
# the same script works against the Linux simulation (docker logs) and against
# hardware (a serial log captured to a file).
#
# The programs run with `_SPEED 0`, which lifts the 60 statements per frame
# pacing -- what is measured is how fast the interpreter can go, not how fast it
# is allowed to go. Comparing the two tells you whether the pacing knob is a
# ceiling the device can actually reach (phase_b5 T5-2).
#
# Usage:
#   tool/basic/basic_bench.rb                    # run in the simulation
#   tool/basic/basic_bench.rb --log serial.txt   # read a captured device log
#
# The simulation run needs the stack up (tools/dev_run_check.sh --keep) and the
# debug daemon port the compose file exposes.

require "open3"

HERE = File.dirname(File.expand_path(__FILE__))
CORE = File.expand_path(File.join(HERE, "..", ".."))
SAMPLES = File.join(CORE, "components", "basic", "test", "samples")
APP_DIR = File.join(CORE, "flash", "app", "demo")
APP_NAME = "_bench"
CONTAINER = "fmruby_core"

# Statement counts, so a duration becomes a rate. Counted from the program text:
# what the interpreter actually executes, one per statement per iteration.
BENCHES = {
  "bench_01_loop"   => { label: "bare loop",   statements: 100 * 1000 * 1 + 100 * 2 },
  "bench_02_expr"   => { label: "expressions", statements: 20_000 * 4 },
  "bench_03_string" => { label: "strings",     statements: 10_000 * 4 },
  # Not a rate: PAUSE 600 should take ten seconds, and how far off it is says
  # how accurate the frame clock is.
  "bench_04_tick"   => { label: "600 frames",  expect: 10.0 },
  # The rate a program actually sees, with the pacing left in place.
  "bench_05_paced"  => { label: "paced loop",  statements: 20 * 100 * 1 + 20 * 2 },
}

# "I (21:24:00.651) tag: text" -> seconds since midnight
def log_time(line)
  m = /\((\d+):(\d+):(\d+)\.(\d+)\)/.match(line)
  return nil unless m
  m[1].to_i * 3600 + m[2].to_i * 60 + m[3].to_i + m[4].to_i / 1000.0
end

def marker_times(lines, name)
  start_at = nil
  end_at = nil
  lines.each do |line|
    next unless line.include?("BENCH ")
    # The interpreter upper cases program text, so the markers arrive upper case.
    start_at ||= log_time(line) if line.include?("BENCH START #{name.upcase}")
    end_at = log_time(line) if line.include?("BENCH END #{name.upcase}")
  end
  [start_at, end_at]
end

def report(name, info, seconds)
  if seconds.nil? || seconds <= 0
    puts format("%-16s %-12s  no markers in the log", name, info[:label])
    return
  end
  if info[:expect]
    error = (seconds - info[:expect]) / info[:expect] * 100.0
    puts format("%-16s %-12s  %7.3f s  expected %.3f s  (%+.1f%%)",
                name, info[:label], seconds, info[:expect], error)
    return
  end
  rate = info[:statements] / seconds
  puts format("%-16s %-12s  %7.3f s  %9.0f statements/s  (%d statements)",
              name, info[:label], seconds, rate, info[:statements])
end

# Spawn one benchmark in the simulation and return the log lines it produced.
def simulation_run(bench)
  src = File.join(SAMPLES, "#{bench}.bas")
  abort "no such benchmark: #{src}" unless File.exist?(src)
  File.write(File.join(APP_DIR, "#{APP_NAME}.app.bas"), File.read(src))
  # background: no screen, so PRINT reaches the log where the timestamps are.
  File.write(File.join(APP_DIR, "#{APP_NAME}.app.toml"), <<~TOML)
    # Generated by tool/basic/basic_bench.rb; removed after the run.
    app_handle_name = "#{APP_NAME}"
    app_screen_name = "Bench"
    default_window_mode = "background"
    launcher_visible = false
  TOML

  spawn_script = <<~PY
    import sys, time
    sys.path.insert(0, "#{File.join(CORE, 'tool', 'debug')}")
    from fmrb_dbg_client import FmrbDebugClient, TcpTransport
    c = FmrbDebugClient(TcpTransport("127.0.0.1", 5555)); c.connect()
    pid = c.spawn("/app/demo/#{APP_NAME}.app.bas")
    c.close()
    print(pid)
  PY
  out, err, status = Open3.capture3("python3", "-c", spawn_script)
  abort "spawn failed: #{err}" unless status.success?

  # Give it room to finish; the benchmarks are seconds, not minutes.
  sleep 30
  logs, = Open3.capture2e("docker", "logs", "--since", "40s", CONTAINER)
  logs.lines
end

def cleanup
  ["#{APP_NAME}.app.bas", "#{APP_NAME}.app.toml"].each do |f|
    path = File.join(APP_DIR, f)
    File.delete(path) if File.exist?(path)
  end
end

def main
  log_file = nil
  if (at = ARGV.index("--log"))
    log_file = ARGV[at + 1]
  end

  puts "benchmark      what          elapsed    rate"
  if log_file
    lines = File.readlines(log_file)
    BENCHES.each do |name, info|
      s, e = marker_times(lines, name.split("_", 3).last)
      report(name, info, s && e ? e - s : nil)
    end
    return 0
  end

  begin
    BENCHES.each do |name, info|
      lines = simulation_run(name)
      s, e = marker_times(lines, name.split("_", 3).last)
      report(name, info, s && e ? e - s : nil)
    end
  ensure
    cleanup
  end
  0
end

exit(main) if __FILE__ == $PROGRAM_NAME
