#!/usr/bin/env ruby
# Generate the placeholder tile set for Family BASIC character table A.
#
# Table A holds the built in animation characters (Mario, Lady, the enemies and
# so on -- core_spec sec 12). Those are Nintendo's artwork, so this project
# cannot ship them; what it ships is a placeholder set that keeps the *code
# positions* meaningful and stays readable on screen, so DEF SPRITE and DEF MOVE
# can be developed and tested. Real artwork is a separate job (00_common, open
# question 2) and only changes this file's output.
#
# The placeholders are procedural on purpose: 16x16 characters occupy four
# consecutive codes (top left, top right, bottom left, bottom right), so each
# tile draws the part of a framed box that its position in the quad calls for,
# plus a body pattern derived from the quad number. A sprite therefore reads as
# one box with a distinguishing pattern rather than four unrelated squares.
#
# Usage:
#     tool/basic/gen_basic_tiles.rb [output.c]
#         default output: components/basic/assets/basic_tile_a.c
#     tool/basic/gen_basic_tiles.rb --bmp sheet.bmp
#         write the art as an editable sheet instead

require_relative "basic_sheet"

CELL = 8

# Colour indices the renderer draws (0 = backdrop / transparent, 1-3 are the
# three colours of the cell's attribute group). The placeholders use all three
# so a look at the screen shows whether the palette is being applied.
INDEX_FRAME = 1
INDEX_BODY = 2
INDEX_MARK = 3

# Set one pixel's 2bpp index in a row (leftmost pixel is the top pair).
def put(rows, x, y, index)
  shift = 14 - 2 * x
  rows[y] = (rows[y] & ~(3 << shift)) | (index << shift)
end

# Draw the border segments this quadrant owns.
#
# part: 0 = top left, 1 = top right, 2 = bottom left, 3 = bottom right.
def quad_frame(rows, part)
  top = [0, 1].include?(part)
  bottom = [2, 3].include?(part)
  left = [0, 2].include?(part)
  right = [1, 3].include?(part)

  CELL.times do |y|
    CELL.times do |x|
      edge = (top && y == 0) || (bottom && y == CELL - 1) ||
             (left && x == 0) || (right && x == CELL - 1)
      put(rows, x, y, INDEX_FRAME) if edge
    end
  end
end

# Fill the inside with a pattern that identifies the character.
def body_pattern(rows, kind, part)
  (1...(CELL - 1)).each do |y|
    (1...(CELL - 1)).each do |x|
      on = case kind
           when 0 then (x + y) % 3 == 0             # diagonal hatch
           when 1 then y.even?                       # horizontal bars
           when 2 then x.even?                       # vertical bars
           when 3 then (x / 2 + y / 2).even?         # coarse checker
           when 4 then (2..5).cover?(x) && (2..5).cover?(y)  # centre block
           when 5 then x == y || x + y == CELL - 1   # cross
           when 6 then (x * y) % 5 == 0              # sparse dots
           else false                                 # hollow
           end
      put(rows, x, y, INDEX_BODY) if on
    end
  end

  # A dot in the quadrant's own corner keeps the four tiles of a 16x16
  # character distinguishable when they are used on their own.
  corner_x = [0, 2].include?(part) ? 1 : CELL - 2
  corner_y = [0, 1].include?(part) ? 1 : CELL - 2
  put(rows, corner_x, corner_y, INDEX_MARK)
end

def build
  (0...256).map do |code|
    rows = Array.new(CELL, 0)
    quad = code / 4          # which 16x16 character this tile belongs to
    part = code % 4          # position inside it
    quad_frame(rows, part)
    body_pattern(rows, quad % 8, part)
    rows
  end
end

def emit_c(glyphs, path)
  lines = [
    "// Generated by tool/basic/gen_basic_tiles.rb -- do not edit by hand.",
    "//",
    "// Placeholder artwork for Family BASIC character table A (the built in",
    "// animation characters). Code positions follow core_spec sec 12; the shapes",
    "// are procedural stand ins for artwork this project cannot ship.",
    "// Two bits per pixel: the leftmost pixel is the top pair of each row.",
    "",
    '#include "basic_tile_a.h"',
    "",
    "const uint16_t basic_tile_a[256][8] = {",
  ]
  256.times do |code|
    rows = glyphs[code].map { |v| format("0x%04X", v) }.join(", ")
    lines << "    {#{rows}},  // #{code}"
  end
  lines << "};"
  lines << ""
  File.write(path, lines.join("\n"))
end

def main
  here = File.dirname(File.expand_path(__FILE__))
  args = ARGV.dup
  bmp = nil
  if (at = args.index("--bmp"))
    bmp = args[at + 1]
    args.slice!(at, 2)
  end
  glyphs = build
  if bmp
    # Export the art as an editable sheet instead of the C table. This
    # overwrites hand edits, so it is never part of the default run.
    BasicSheet.write_bmp(BasicSheet.glyphs_to_pixels(glyphs), bmp)
    puts "wrote #{bmp}"
    return
  end
  default = File.join(here, "..", "..", "components", "basic", "assets", "basic_tile_a.c")
  out = args[0] || File.expand_path(default)
  emit_c(glyphs, out)
  puts "wrote #{out}"
end

main if __FILE__ == $PROGRAM_NAME
