# Area512 built-in type declaration.

class Hash
  include Enumerable
  # 等しいかどうか <<en>> Perform equality comparison
  def ==: (untyped other) -> bool

  # そのキーの値を返す <<en>> Get value for specified key
  def []: (untyped key) -> untyped

  # そのキーに値を入れる <<en>> Set value for specified key
  def []=: (untyped key, untyped value) -> self

  # ハッシュを空にする <<en>> Remove all elements from hash
  def clear: () -> Hash

  # そのキーを消す <<en>> Delete specified key
  def delete: (untyped key) -> (untyped | nil)

  # キーと値の組ごとにブロックを実行する <<en>> Execute block for each key and value
  def each: () { (untyped key, untyped value) -> untyped } -> self

  # ハッシュが空かどうか <<en>> Check if hash is empty
  def empty?: () -> bool

  # そのキーがあるかどうか <<en>> Check if specified key exists
  def has_key?: (untyped key) -> bool

  # その値があるかどうか <<en>> Check if specified value exists
  def has_value?: (untyped value) -> bool

  # 中身が分かる形の文字列を返す <<en>> Return string representation for debugging
  def inspect: () -> String

  def key: (untyped value) -> (untyped | nil)

  # キーを全部配列で返す <<en>> Return all keys as array
  def keys: () -> Array[untyped]

  # 要素の数を返す <<en>> Return number of elements in hash
  def length: () -> Integer

  # 他のハッシュと合わせた新しいハッシュを返す <<en>> Return new hash merged with another hash
  def merge: (Hash other) -> self

  # 自分に他のハッシュを取り込む <<en>> Merge hash destructively
  def merge!: (Hash other) -> self

  # 自分自身をハッシュとして返す <<en>> Return self as hash
  def to_h: () -> self

  # 値を全部配列で返す <<en>> Return all values as array
  def values: () -> Array[untyped]

  def self.new: () -> Hash

end
