# Area512 built-in type declaration.

class Integer
  # 割ったあまりを求める <<en>> Calculate modulo
  def %: ((Integer | Float) other) -> (Integer | Float)

  # ビットごとの論理積を求める <<en>> Perform bitwise AND operation
  def &: (Integer other) -> Integer

  # かけ算をする <<en>> Perform multiplication
  def *: ((Integer | Float) other) -> (Integer | Float)

  # べき乗を求める <<en>> Calculate power
  def **: ((Integer | Float) other) -> Integer

  # 足し算をする <<en>> Perform addition
  def +: ((Integer | Float) other) -> (Integer | Float)

  # 自分自身を返す (単項プラス) <<en>> Unary plus operator. Returns self
  def +@: () -> Integer

  # 引き算をする <<en>> Perform subtraction
  def -: ((Integer | Float) other) -> (Integer | Float)

  # 符号を反転する (単項マイナス) <<en>> Unary minus operator. Inverts sign
  def -@: () -> Integer

  # 割り算をする <<en>> Perform division
  def /: ((Integer | Float) other) -> (Integer | Float)

  # より小さいかどうか <<en>> Perform less than comparison
  def <: ((Integer | Float) other) -> bool

  # ビットを左にずらす <<en>> Perform left bit shift
  def <<: (Integer other) -> Integer

  # 以下かどうか <<en>> Perform less than or equal comparison
  def <=: ((Integer | Float) other) -> bool

  # 大小を比べて -1 / 0 / 1 を返す <<en>> Compare. Returns -1, 0 or 1
  def <=>: ((Integer | untyped) other) -> Integer

  # 等しいかどうか <<en>> Perform equality comparison
  def ==: (untyped other) -> bool

  # より大きいかどうか <<en>> Perform greater than comparison
  def >: ((Integer | Float) other) -> bool

  # 以上かどうか <<en>> Perform greater than or equal comparison
  def >=: ((Integer | Float) other) -> bool

  # ビットを右にずらす <<en>> Perform right bit shift
  def >>: (Integer other) -> Integer

  # ビットごとの排他的論理和を求める <<en>> Perform bitwise XOR operation
  def ^: (Integer other) -> Integer

  # その位置のビットを返す <<en>> Get value at specified bit position
  def []: (untyped index) -> Integer

  # 絶対値を返す <<en>> Get absolute value
  def abs: () -> Integer

  # 文字コードに対応する 1 文字を返す <<en>> Return the character for this code
  def chr: () -> String

  # 自分から引数まで 1 ずつ減らして実行 <<en>> Run the block from self down to the argument
  def downto: (Integer limit) { (Integer block_limit) -> untyped } -> Integer

  # 自分の回数だけブロックを実行する <<en>> Execute block self times
  def times: () { (Integer index) -> untyped } -> Integer

  # 小数に変える <<en>> Convert to floating point number
  def to_f: () -> Float

  # 自分自身を整数として返す <<en>> Return self as integer value
  def to_i: () -> Integer

  # 文字列に変える。基数は引数で指定 <<en>> Convert to string. Base can be specified with argument
  def to_s: (?Integer base) -> String

  # ビットごとの論理和を求める <<en>> Perform bitwise OR operation
  def |: (Integer other) -> Integer

  # ビットを反転する <<en>> Perform bitwise NOT operation
  def ~: () -> Integer

end
