# Area512 built-in type declaration.

module Kernel
  # 中身が分かる形で出力する <<en>> Inspect and output object
  def p: (*untyped objects) -> untyped

  # 出力する <<en>> Output object
  def print: (*untyped objects) -> nil

  # 改行をつけて出力する <<en>> Output object with newline
  def puts: (*untyped objects) -> nil

  def yield: (*untyped arguments) -> untyped

  # Proc を作る <<en>> Create Proc object
  def proc: () { (untyped argument) -> untyped } -> Proc

  # lambda を作る <<en>> Create lambda expression
  def lambda: () { (untyped argument) -> untyped } -> Proc

  def `->`: (untyped argument) { (untyped block_argument) -> untyped } -> Proc

end
