# Area512 built-in type declaration.

class NilClass
  def !: () -> bool

  # 常に false を返す <<en>> Always returns false
  def &: (untyped other) -> bool

  def ===: (untyped other) -> bool

  # 引数の真偽を返す <<en>> Returns logical value of argument
  def ^: (untyped other) -> bool

  # "nil" という文字列を返す <<en>> Returns "nil"
  def inspect: () -> String

  # 常に true を返す <<en>> Returns true
  def nil?: () -> bool

  # 0.0 を返す <<en>> Returns 0.0
  def to_f: () -> Float

  # 空のハッシュを返す <<en>> Returns empty hash
  def to_h: () -> Hash

  # 0 を返す <<en>> Returns 0
  def to_i: () -> Integer

  # 空の文字列を返す <<en>> Returns empty string
  def to_s: () -> String

  # 引数の真偽を返す <<en>> Returns logical value of argument
  def |: (untyped other) -> bool

end
