# Area512 built-in type declaration.

class Object
  include Kernel
  # 大小を比べる <<en>> Comparison operator
  def <=>: (untyped other) -> Integer

  # 等しくないかどうか <<en>> Perform inequality comparison
  def !=: (untyped other) -> bool

  # 等しいかどうか <<en>> Perform equality comparison
  def ==: (untyped other) -> bool

  # case での一致を判定する <<en>> Judge case equality
  def ===: (untyped other) -> bool

  def attr_accessor: (*Symbol names) -> nil

  def attr_reader: (*Symbol names) -> nil

  def block_given?: () -> bool

  # そのオブジェクトのクラスを返す <<en>> Return object class
  def class: () -> Class

  # 複製を作る <<en>> Duplicate object
  def dup: () -> self

  def exit: (?Integer status) -> nil

  def include: (*untyped modules) -> nil

  def extend: (*untyped modules) -> nil

  # 中身が分かる形の文字列を返す <<en>> Return string representation for debugging
  def inspect: () -> String

  # そのクラスかモジュールに属するか <<en>> Check if instance of specified class or module
  def is_a?: (untyped class_or_module) -> bool

  def loop: () { (nil value) -> untyped } -> nil

  # nil かどうか <<en>> Check if nil
  def nil?: () -> bool

  def private: (*Symbol names) -> nil

  def public: (*Symbol names) -> nil

  def raise: (?untyped exception, ?String message) -> bot

  def relinquish: () -> bool

  def sleep: ((Integer | Float) duration) -> Integer

  def sleep_ms: (Integer milliseconds) -> Integer

  def sprintf: (String format, *untyped arguments) -> String

  # 文字列にして返す <<en>> Return string representation
  def to_s: () -> String

  # メソッドの一覧を返す <<en>> get object method list
  def self.methods: () -> Array[Symbol]

end
