# Area512 built-in type declaration.

class Range < Enumerable
  # 等しいかどうか <<en>> Perform equality comparison
  def ==: (untyped other) -> bool

  # 範囲に含まれるかどうか <<en>> Check if value is included in range
  def ===: (untyped object) -> bool

  # 終わりの値を含まない範囲かどうか <<en>> Check if end value is excluded
  def exclude_end?: () -> bool

  # 範囲の始まりの値を返す <<en>> Return start value of range
  def first: () -> untyped

  # 中身が分かる形の文字列を返す <<en>> Return string representation for debugging
  def inspect: () -> String

  # 範囲の終わりの値を返す <<en>> Return end value of range
  def last: () -> untyped

  # 文字列にして返す <<en>> Return string representation
  def to_s: () -> String

  # 範囲の要素ごとにブロックを実行する <<en>> Execute block for each element in range
  def each: () { (untyped element) -> untyped } -> self

  def self.new: (untyped first, untyped last, ?bool exclude_end) -> Range

end
