# Area512 built-in type declaration.

class Symbol
  # シンボルを比べる <<en>> Compare symbols
  def <=>: ((Symbol | untyped) other) -> Integer

  # 等しいかどうか <<en>> Perform equality comparison
  def ==: (untyped other) -> bool

  # case での等しさを判定する <<en>> Perform equality comparison (for case statements)
  def ===: (untyped other) -> bool

  # 中身が分かる形の文字列を返す <<en>> Return string representation for debugging
  def inspect: () -> String

  # 自分自身をシンボルとして返す <<en>> Return self as symbol
  def to_sym: () -> Symbol

end
