app_screen_name = "GPIO Viewer"
app_screen_name_ja = "GPIO表示"
default_window_mode = "window"
default_window_width = 300
default_window_height = 180
default_window_pos_x = 20
default_window_pos_y = 20
launcher_visible = false