app_handle_name = "smf_player"
app_screen_name = "SMF Player"
app_screen_name_ja = "SMFプレーヤ"
default_window_mode = "window"
default_window_width = 280
default_window_height = 200
default_window_pos_x = 10
default_window_pos_y = 15
