# script name must be "app_handle_name.app.bas"
app_handle_name = "sample_basic_app"
app_screen_name = "BASIC app"
#default_window_mode = "background" # or "fullwindow" or "window" or "background"
default_window_mode = "window" # or "fullwindow" or "window" or "background"

# if fullscreen/fullwindow, they will be ignored
default_window_width = 200
default_window_height = 150

# if fullscreen/fullwindow, they will be ignored
default_window_pos_x = 10
default_window_pos_y = 15
