app_handle_name = "midi_apu"
app_screen_name = "MIDI APU"
app_screen_name_ja = "MIDI音源"
default_window_mode = "window"
default_window_width = 160
default_window_height = 196
default_window_pos_x = 40
default_window_pos_y = 40
