app_handle_name = "picoruby"
app_screen_name = "PicoRuby demo"
app_screen_name_ja = "PicoRubyデモ"

default_window_mode = "window"

default_window_width = 300
default_window_height = 214

default_window_pos_x = 10
default_window_pos_y = 20
