/*
 * The receiver for the Spinel raycaster: an mruby app task builds a Spinel
 * instance beside its own VM, calls the Spinel-compiled entries the way it
 * would call C functions, and tears the instance down. That works because an
 * instance is per-task state (fmrb_spinel_host.h) and mruby's mrb_state knows
 * nothing about it. See doc/spinel_aot/adding_a_spinel_gem.md.
 *
 * spinel/raycast_kernel.rb is compiled as a Spinel ext program; its generated
 * header declares Init_raycast() and the two entries as typed C functions:
 * load_map takes the map as a String, cast takes the player as three ints and
 * returns the packed depth buffer as a String. This file includes that header,
 * so it is compiled with the same flags as the generated program
 * (SPINEL_GEN_TU_FLAGS in main/CMakeLists.txt).
 *
 * Placement: the statics here go to PSRAM on the device. Internal DRAM is the
 * scarce resource and nothing in this file is on a hardware path.
 */
#include <stdint.h>
#include <string.h>
#include <time.h>

#include "raycast_kernel.h"   /* generated by rake spinel:gen */
#include "raycast_native.h"
#include "fmrb_log.h"
#include "fmrb_mem.h"
#include "fmrb_spinel_host.h"

#ifdef CONFIG_IDF_TARGET_LINUX
#define RC_BSS_ATTR
#else
#include "esp_attr.h"
#define RC_BSS_ATTR EXT_RAM_BSS_ATTR
#endif

static const char *TAG = "raycast";

/* The core the program keeps holds the map plus two 360-entry trig tables,
   and the transient String per frame on top. 128 KB leaves the collector room
   to work rather than thrash; it comes from fmrb_sys_malloc, which is PSRAM,
   so a demo nobody launches costs no internal RAM. */
#define RC_POOL_BYTES (128 * 1024)

RC_BSS_ATTR static void *s_pool;
RC_BSS_ATTR static void *s_est;
RC_BSS_ATTR static int   s_open;
RC_BSS_ATTR static int   s_have_map;

/* Every call into the program goes through Init_raycast_try: a Ruby raise that
   escapes it would otherwise end the whole firmware. */
typedef struct {
    const char *map;
    int         px, py, pa, w, h;
    const char *out;
} rc_call_t;

static void rc_init(void *p) { (void)p; Init_raycast(); }
static void rc_load(void *p) { rc_call_t *c = (rc_call_t *)p; sp_RaycastKernel_s_load_map(c->map, c->w, c->h); }
static void rc_cast(void *p) { rc_call_t *c = (rc_call_t *)p; c->out = sp_RaycastKernel_s_cast(c->px, c->py, c->pa); }

static int rc_try(void (*fn)(void *), void *arg, const char *what)
{
    const char *cls = NULL, *msg = NULL;
    if (Init_raycast_try(fn, arg, &cls, &msg)) {
        FMRB_LOGE(TAG, "%s raised %s: %s", what, cls ? cls : "?", msg ? msg : "");
        return -1;
    }
    return 0;
}

int raycast_available(void)
{
    return 1;
}

uint32_t raycast_micros(void)
{
    /* One clock for both backends, so the two numbers the demo shows mean the
       same thing. The IDF provides clock_gettime on the device as well. */
    struct timespec ts;
    clock_gettime(CLOCK_MONOTONIC, &ts);
    return (uint32_t)((uint64_t)ts.tv_sec * 1000000u + (uint64_t)ts.tv_nsec / 1000u);
}

int raycast_begin(void)
{
    if (s_open) {
        return 0;
    }
    s_pool = fmrb_sys_malloc(RC_POOL_BYTES);
    if (!s_pool) {
        FMRB_LOGE(TAG, "no memory for the Spinel raycast pool (%d bytes)", RC_POOL_BYTES);
        return -2;
    }
    /* Same threshold rule as the other Spinel instances: collect early so a
       burst of allocation cannot reach the top of the pool, since exhaustion
       goes through sp_oom_die and takes the firmware with it. */
    size_t threshold = RC_POOL_BYTES / 32;
    s_est = fmrb_spinel_instance_begin(s_pool, RC_POOL_BYTES, threshold, threshold);
    if (!s_est) {
        FMRB_LOGE(TAG, "could not create the Spinel raycast instance");
        fmrb_sys_free(s_pool);
        s_pool = NULL;
        return -3;
    }
    if (rc_try(rc_init, NULL, "init") != 0) {
        fmrb_spinel_instance_end(s_est);
        s_est = NULL;
        fmrb_sys_free(s_pool);
        s_pool = NULL;
        return -4;
    }
    s_open = 1;
    s_have_map = 0;
    FMRB_LOGI(TAG, "Spinel raycast instance up (%d bytes)", RC_POOL_BYTES);
    return 0;
}

int raycast_set_map(const uint8_t *cells, int w, int h)
{
    if (!cells || w < 1 || h < 1) {
        return -1;
    }
    if (w * h > RAYCAST_MAP_MAX) {
        FMRB_LOGE(TAG, "map %dx%d is larger than the %d cells this holds", w, h, RAYCAST_MAP_MAX);
        return -2;
    }
    if (!s_open) {
        return -3;
    }
    /* A Spinel String carries its length in a header in front of the bytes,
       so the map is copied onto the instance's heap rather than passed as a C
       buffer. The program builds its core from it and keeps both. */
    rc_call_t c = { sp_str_from_bytes((const char *)cells, (size_t)(w * h)), 0, 0, 0, w, h, NULL };
    if (rc_try(rc_load, &c, "load_map") != 0) {
        return -4;
    }
    s_have_map = 1;
    return 0;
}

const char *raycast_run(int px, int py, int pa, int *out_len, uint32_t *out_us)
{
    if (out_len) *out_len = 0;
    if (out_us) *out_us = 0;
    if (!s_open || !s_have_map) {
        return NULL;
    }
    rc_call_t c = { NULL, px, py, pa, 0, 0, NULL };
    uint32_t t0 = raycast_micros();
    int rc = rc_try(rc_cast, &c, "cast");
    uint32_t us = raycast_micros() - t0;
    if (rc != 0 || !c.out) {
        return NULL;
    }
    if (out_len) *out_len = (int)sp_str_byte_len(c.out);
    if (out_us) *out_us = us;
    /* The core's own output buffer, on the instance's heap: rewritten by the
       next cast and gone after end(), which is the lifetime the header
       promises. */
    return c.out;
}

void raycast_end(void)
{
    if (!s_open) {
        return;
    }
    fmrb_spinel_instance_end(s_est);
    s_est = NULL;
    fmrb_sys_free(s_pool);
    s_pool = NULL;
    s_open = 0;
    s_have_map = 0;
}
