#!/usr/bin/env ruby
# Import a snapshot of the Spinel runtime from the fork checkout into
# components/fmrb_spinel_rt/spinel_rt/. The snapshot is checked in for
# reproducibility (the firmware does not build from tmp/spinel directly).
#
# Usage:
#   ruby components/fmrb_spinel_rt/import_from_fork.rb [FORK_DIR]
# FORK_DIR defaults to ../../../tmp/spinel relative to this script
# (i.e. family-mruby/tmp/spinel).
#
# Design (see doc/spinel_aot/phase1.md T1-4 and the phase1 report):
# - ALL runtime headers are copied: sp_runtime.h includes sp_re.h / sp_time.h /
#   sp_marshal.h / sp_random.h / sp_fiber.h / sp_sched.h / sp_system.h, so those
#   headers must be present even though we do NOT compile their .c.
# - Only a minimal set of .c is copied+compiled (COMPILE_SRCS). regexp / bigint /
#   fiber / sched / net / system / crypto / pack / time / random are excluded;
#   -ffunction-sections + --gc-sections drops any uncalled references to them.
#   If a generated program needs one (e.g. Time / Random), add its .c here.

require "fileutils"
require "digest"

SCRIPT_DIR = File.expand_path(File.dirname(__FILE__))
DEST = File.join(SCRIPT_DIR, "spinel_rt")
fork_dir = ARGV[0] || File.expand_path("../../../tmp/spinel", SCRIPT_DIR)
LIB = File.join(fork_dir, "lib")

abort "fork lib not found: #{LIB}" unless Dir.exist?(LIB)

# Every header sp_runtime.h (transitively) needs. Copy the whole header set --
# it is small and keeps the include graph intact.
HEADERS = Dir.glob(File.join(LIB, "*.h")).map { |p| File.basename(p) }.sort

# Minimal compiled runtime. Kept in sync with CMakeLists.txt COMPILE_SRCS.
COMPILE_SRCS = %w[
  sp_gc.c sp_alloc.c sp_core.c sp_string.c sp_str.c
  sp_array.c sp_inspect.c sp_format.c sp_cold.c sp_io.c
]

FileUtils.mkdir_p(DEST)
# clear old snapshot (only the files we manage: *.c/*.h)
Dir.glob(File.join(DEST, "*.{c,h}")).each { |p| File.delete(p) }

copied = []
(HEADERS + COMPILE_SRCS).each do |name|
  src = File.join(LIB, name)
  unless File.exist?(src)
    warn "SKIP missing #{name}"
    next
  end
  FileUtils.cp(src, File.join(DEST, name))
  copied << name
end

# record provenance
rev = `git -C #{fork_dir} rev-parse HEAD 2>/dev/null`.strip
branch = `git -C #{fork_dir} rev-parse --abbrev-ref HEAD 2>/dev/null`.strip
File.open(File.join(SCRIPT_DIR, "spinel_rt", "IMPORT_INFO"), "w") do |f|
  f.puts "# Spinel runtime snapshot -- generated by import_from_fork.rb; do not edit by hand."
  f.puts "fork_dir: #{fork_dir}"
  f.puts "fork_branch: #{branch}"
  f.puts "fork_commit: #{rev}"
  f.puts "headers: #{HEADERS.size}"
  f.puts "compile_srcs: #{COMPILE_SRCS.join(' ')}"
  f.puts "files:"
  copied.sort.each do |name|
    sum = Digest::SHA1.hexdigest(File.read(File.join(DEST, name)))
    f.puts "  #{name} #{sum[0, 12]}"
  end
end

puts "Imported #{copied.size} files from #{fork_dir} (#{branch} #{rev[0, 12]})"
puts "  headers: #{HEADERS.size}, compiled: #{COMPILE_SRCS.size}"
