#!/usr/bin/env ruby
# Import a snapshot of the Spinel runtime from the fork checkout into
# components/fmrb_spinel_rt/spinel_rt/. The snapshot is checked in for
# reproducibility (the firmware does not build from tmp/spinel directly).
#
# Usage:
#   ruby components/fmrb_spinel_rt/import_from_fork.rb [FORK_DIR]
# FORK_DIR defaults to ../../../tmp/spinel relative to this script
# (i.e. family-mruby/tmp/spinel).
#
# Design (see doc/spinel_aot/phase1.md T1-4 and the phase1 report):
# - ALL runtime headers are copied: sp_runtime.h includes sp_re.h / sp_time.h /
#   sp_marshal.h / sp_random.h / sp_fiber.h / sp_sched.h / sp_system.h, so those
#   headers must be present even though we do NOT compile their .c.
# - Only a minimal set of .c is copied+compiled (COMPILE_SRCS). regexp / bigint /
#   fiber / sched / net / system / crypto / pack / time / random are excluded;
#   -ffunction-sections + --gc-sections drops any uncalled references to them.
#   If a generated program needs one (e.g. Time / Random), add its .c here.

require "fileutils"
require "digest"

SCRIPT_DIR = File.expand_path(File.dirname(__FILE__))
DEST = File.join(SCRIPT_DIR, "spinel_rt")
fork_dir = ARGV[0] || File.expand_path("../../../tmp/spinel", SCRIPT_DIR)
LIB = File.join(fork_dir, "lib")

abort "fork lib not found: #{LIB}" unless Dir.exist?(LIB)

# Every header sp_runtime.h (transitively) needs, plus the regexp engine
# headers. Copy the whole header set (flattened) -- it is small and keeps the
# include graph intact.
HEADERS = (Dir.glob(File.join(LIB, "*.h")) +
           Dir.glob(File.join(LIB, "regexp", "*.h"))).map { |p| File.basename(p) }.sort

# Compiled runtime. sp_runtime.h's static helpers cross-reference most modules
# (e.g. sp_poly_inspect -> bigint / regexp; sp_re_mark_globals -> fiber), so a
# truly minimal set does not link -- compile the whole runtime except the
# modules with external OS dependencies the kernel does not use:
#   - sp_net.c    (BSD sockets)
#   - sp_crypto.c (libcrypt; String#crypt)
# Their unused callers are dropped by -ffunction-sections + --gc-sections.
EXCLUDE_C = %w[sp_net.c sp_crypto.c].freeze
COMPILE_SRCS = (Dir.glob(File.join(LIB, "sp_*.c")).map { |p| File.basename(p) } -
                EXCLUDE_C).sort +
               Dir.glob(File.join(LIB, "regexp", "*.c")).map { |p| File.basename(p) }.sort

FileUtils.mkdir_p(DEST)
# clear old snapshot (only the files we manage: *.c/*.h)
Dir.glob(File.join(DEST, "*.{c,h}")).each { |p| File.delete(p) }

copied = []
# headers may live in lib/ or lib/regexp/; find each by basename
find_src = lambda do |name|
  [File.join(LIB, name), File.join(LIB, "regexp", name)].find { |p| File.exist?(p) }
end
(HEADERS + COMPILE_SRCS).each do |name|
  src = find_src.call(name)
  unless src
    warn "SKIP missing #{name}"
    next
  end
  FileUtils.cp(src, File.join(DEST, name))
  copied << name
end

# record provenance
rev = `git -C #{fork_dir} rev-parse HEAD 2>/dev/null`.strip
branch = `git -C #{fork_dir} rev-parse --abbrev-ref HEAD 2>/dev/null`.strip
File.open(File.join(SCRIPT_DIR, "spinel_rt", "IMPORT_INFO"), "w") do |f|
  f.puts "# Spinel runtime snapshot -- generated by import_from_fork.rb; do not edit by hand."
  f.puts "fork_dir: #{fork_dir}"
  f.puts "fork_branch: #{branch}"
  f.puts "fork_commit: #{rev}"
  f.puts "headers: #{HEADERS.size}"
  f.puts "compile_srcs: #{COMPILE_SRCS.join(' ')}"
  f.puts "files:"
  copied.sort.each do |name|
    sum = Digest::SHA1.hexdigest(File.read(File.join(DEST, name)))
    f.puts "  #{name} #{sum[0, 12]}"
  end
end

puts "Imported #{copied.size} files from #{fork_dir} (#{branch} #{rev[0, 12]})"
puts "  headers: #{HEADERS.size}, compiled: #{COMPILE_SRCS.size}"
