# rakelib/basic.rake
# Family BASIC: host golden tests, sample/benchmark and art staging.
# Part of the Rakefile split: shared constants, helper defs, and the
# docker command strings live in the top-level Rakefile, which Rake
# loads before every file in rakelib/.

namespace :basic do
  # Family BASIC golden tests. The interpreter core (components/basic/core) is
  # host independent pure C++, so the tests build with the host g++ and need
  # neither docker nor an IDF checkout. Flags mirror the firmware constraints
  # (C++20, no exceptions, no RTTI) so a violation fails here first.
  BASIC_DIR        = "components/basic"
  BASIC_TEST_DIR   = "#{BASIC_DIR}/test"
  BASIC_TEST_BUILD = "#{BASIC_TEST_DIR}/build"
  BASIC_RUNNER_BIN = "#{BASIC_TEST_BUILD}/basic_runner"
  BASIC_TEST_SRCS  = Dir["#{BASIC_DIR}/core/*.cpp"].sort + ["#{BASIC_TEST_DIR}/runner/main.cpp"]
  BASIC_CXXFLAGS   = %w[
    -std=c++20 -O1 -g
    -fno-exceptions -fno-rtti
    -Wall -Wextra -Werror
  ].join(" ")

  desc "Build the host BASIC golden test runner (g++, no docker)"
  task :runner do
    cxx = ENV["CXX"] || "g++"
    abort "#{cxx} not found (install g++ or set CXX)" unless system("which #{cxx} > /dev/null 2>&1")
    mkdir_p BASIC_TEST_BUILD
    sh "#{cxx} #{BASIC_CXXFLAGS} -I #{BASIC_DIR}/core " \
       "#{BASIC_TEST_SRCS.join(' ')} -o #{BASIC_RUNNER_BIN}"
  end

  desc "Run the BASIC golden tests (FILTER=name to run a subset)"
  task :test => :runner do
    filter = ENV["FILTER"].to_s
    sh "#{BASIC_TEST_DIR}/run_golden.sh #{BASIC_RUNNER_BIN} #{filter}".strip
  end

  desc "Run one .bas through the host runner (BAS=path [IN=path])"
  task :run => :runner do
    bas = ENV["BAS"] or abort "usage: rake basic:run BAS=path/to/program.bas [IN=input.txt]"
    sh "#{BASIC_RUNNER_BIN} #{bas} #{ENV['IN']}".strip
  end

  desc "Remove the host BASIC test build"
  task :clean do
    rm_rf BASIC_TEST_BUILD
  end

  # Samples that are meant to be played by hand (keys, sound, sprites). The
  # launcher scans /app/<category>/*.app.toml, so a copy under flash/app/basic
  # turns each one into a double-clickable app on the desktop -- unlike a
  # debugd spawn, a launcher start also gets the keyboard focus.
  # test/samples stays the single source: re-run this task after editing a
  # sample and commit the refreshed copies.
  BASIC_SAMPLE_APPS = {
    "sample_04_screen_kana" => ["Kana",  "カナ"],
    "sample_10_dodge"       => ["Dodge", "ヨケロ"],
    "sample_11_shoot"       => ["Shoot", "シュート"],
    "sample_12_maze"        => ["Maze",  "メイロ"],
    "sample_13_music"       => ["Music", "オンガク"],
    "sample_14_hit"         => ["Hit",   "タタケ"],
  }
  BASIC_SAMPLE_APP_DIR = "flash/app/basic"

  # Character sheets. The firmware loads flash/usr/share/basic/*.bmp at app
  # start and falls back to the compiled tables when a sheet is missing, so the
  # artwork can be edited in a graphics editor without a rebuild.
  BASIC_SHEET_DIR = "flash/usr/share/basic"
  BASIC_SHEETS = {
    "font_b" => "gen_basic_font.rb",   # table B: text glyphs
    "tile_a" => "gen_basic_tiles.rb",  # table A: sprite tiles
  }

  desc "Export the built-in art to the editable BMP sheets (FORCE=1 to overwrite)"
  task :sheets do
    mkdir_p BASIC_SHEET_DIR
    BASIC_SHEETS.each do |name, gen|
      bmp = "#{BASIC_SHEET_DIR}/#{name}.bmp"
      if File.exist?(bmp) && ENV["FORCE"] != "1"
        puts "keeping #{bmp} (hand edits are the source now; FORCE=1 to overwrite)"
        next
      end
      sh "ruby tool/basic/#{gen} --bmp #{bmp}"
    end
  end

  desc "Convert a character sheet between PNG and BMP (IN=a.png OUT=b.bmp)"
  task :sheet_convert do
    src = ENV["IN"] or abort "usage: rake basic:sheet_convert IN=sheet.png OUT=sheet.bmp"
    dst = ENV["OUT"] or abort "usage: rake basic:sheet_convert IN=sheet.png OUT=sheet.bmp"
    sh "python3 tool/basic/basic_sheet_convert.py #{src} #{dst}"
  end

  desc "Copy the BASIC samples into flash/app/basic so the launcher lists them"
  task :samples do
    mkdir_p BASIC_SAMPLE_APP_DIR
    BASIC_SAMPLE_APPS.each do |base, (label, label_ja)|
      src = "#{BASIC_TEST_DIR}/samples/#{base}.bas"
      abort "missing sample: #{src}" unless File.exist?(src)
      cp src, "#{BASIC_SAMPLE_APP_DIR}/#{base}.app.bas", verbose: true
      File.write("#{BASIC_SAMPLE_APP_DIR}/#{base}.app.toml", <<~TOML)
        # Generated by "rake basic:samples" from #{BASIC_TEST_DIR}/samples.
        # Edit the sample there, not this copy.
        app_handle_name = "#{base}"
        app_screen_name = "#{label}"
        app_screen_name_ja = "#{label_ja}"
      TOML
    end
    puts "#{BASIC_SAMPLE_APPS.size} samples installed in #{BASIC_SAMPLE_APP_DIR}"
  end

  # The benchmarks have to be on the device to be run there: the editor opens
  # files from the device filesystem, and test/samples/ only exists on the host.
  # /home rather than /app/basic so they stay out of the launcher -- they are a
  # measuring tool, not something to browse to.
  BASIC_BENCH_DIR = "flash/home/bench"

  desc "Copy the BASIC benchmarks into flash/home/bench (needs a reflash to reach the device)"
  task :bench do
    mkdir_p BASIC_BENCH_DIR
    installed = 0
    Dir["#{BASIC_TEST_DIR}/samples/bench_*.bas"].sort.each do |src|
      base = File.basename(src, ".bas")
      cp src, "#{BASIC_BENCH_DIR}/#{base}.bas", verbose: true
      # A benchmark reports through the log, and the log only carries PRINT when
      # the app has no screen -- otherwise the text belongs on the screen and
      # mirroring it would flood the log. So each one runs in background mode.
      File.write("#{BASIC_BENCH_DIR}/#{base}.toml", <<~TOML)
        # Generated by "rake basic:bench" from #{BASIC_TEST_DIR}/samples.
        app_handle_name = "#{base}"
        app_screen_name = "#{base}"
        default_window_mode = "background"
      TOML
      installed += 1
    end
    abort "no benchmarks in #{BASIC_TEST_DIR}/samples" if installed.zero?
    puts "#{installed} benchmarks installed in #{BASIC_BENCH_DIR}"
    puts "run 'rake build:esp32 && rake flash' to put them on the device"
    puts "remove them again with 'rake basic:bench_clean'"
  end

  desc "Remove the benchmarks from flash/home/bench"
  task :bench_clean do
    rm_rf BASIC_BENCH_DIR
    puts "removed #{BASIC_BENCH_DIR}"
  end
end
