# rakelib/micropython.rake
# MicroPython embed port: regen, prelude header, and host smoke test.
# Part of the Rakefile split: shared constants, helper defs, and the
# docker command strings live in the top-level Rakefile, which Rake
# loads before every file in rakelib/.

namespace :micropython do
  # MicroPython is taken in through its "embed" port: one make run turns the
  # submodule plus port/mpconfigport.h into a self-contained C tree (qstr and
  # module tables already generated) under components/micropython/mp_embed.
  # That tree is committed, so rake build:linux / build:esp32 compile plain C
  # and need neither make nor python3 -- only :gen does. Re-run :gen after
  # editing mpconfigport.h or anything under modules/, and commit the result.
  MP_DIR         = "components/micropython"
  MP_SUBMODULE   = "#{MP_DIR}/micropython"
  MP_PORT_DIR    = "#{MP_DIR}/port"
  MP_EMBED_DIR   = "#{MP_DIR}/mp_embed"
  MP_GEN_BUILD   = "#{MP_PORT_DIR}/build-embed"
  MP_SMOKE_DIR   = "#{MP_PORT_DIR}/test"
  MP_SMOKE_BUILD = "#{MP_SMOKE_DIR}/build"
  MP_SMOKE_BIN   = "#{MP_SMOKE_BUILD}/mp_smoke"
  # The generated tree uses GNU C extensions (the GC helper pins registers with
  # "register ... asm"), so a strict -std=c99 compile of it does not work.
  MP_SMOKE_CFLAGS = "-std=gnu99 -Os -Wall -fno-common"

  # The component CMakeLists includes this file rather than globbing, so the
  # file list is reviewable in a diff and can never silently go stale: it is
  # rewritten by the same task that rewrites the sources it lists.
  MP_EMBED_SRCS_CMAKE = "#{MP_DIR}/mp_embed_srcs.cmake"

  desc "Regenerate #{MP_EMBED_DIR} from the submodule (needs make + python3)"
  task :gen => :prelude do
    unless File.exist?("#{MP_SUBMODULE}/ports/embed/embed.mk")
      abort "#{MP_SUBMODULE} is empty. Run 'git submodule update --init #{MP_SUBMODULE}'"
    end
    sh "make -C #{MP_PORT_DIR}"

    srcs = Dir["#{MP_EMBED_DIR}/**/*.c"].sort.map { |p| p.sub("#{MP_DIR}/", "") }
    abort "no sources under #{MP_EMBED_DIR}" if srcs.empty?
    File.write(MP_EMBED_SRCS_CMAKE, <<~CMAKE)
      # Generated by "rake micropython:gen" -- do not edit.
      # Source list of the MicroPython embed package. Regenerated together with
      # mp_embed/ itself, so the two can never drift apart.
      set(MP_EMBED_SRCS
      #{srcs.map { |s| "    \"#{s}\"" }.join("\n")}
      )
    CMAKE

    puts "regenerated #{MP_EMBED_DIR} (#{srcs.size} sources) and #{MP_EMBED_SRCS_CMAKE}"
    puts "commit both along with the change that caused the regeneration"
  end

  # The Python half of the app framework. These are not modules even though
  # the guest can import now: they are concatenated in this order and executed
  # in the app's own global namespace just before the user script, which is
  # what makes FmrbApp and FmrbGfx visible to it the way the Ruby framework's
  # classes are visible to a .rb app. (The flip side is that a module the app
  # imports does not see them -- see doc/micropython/known_limitations.md.)
  MP_PRELUDE_DIR = "#{MP_DIR}/prelude"
  MP_PRELUDE_FILES = ["fmrb_gfx.py", "fmrb_app.py"]
  MP_PRELUDE_HEADER = "#{MP_PRELUDE_DIR}/fmrb_prelude.h"

  desc "Regenerate #{MP_PRELUDE_HEADER} from #{MP_PRELUDE_DIR}/*.py"
  task :prelude do
    src = MP_PRELUDE_FILES.map do |name|
      path = "#{MP_PRELUDE_DIR}/#{name}"
      abort "missing prelude source: #{path}" unless File.exist?(path)
      "# --- #{name} ---\n#{File.read(path)}"
    end.join("\n")

    # One C string literal per line keeps the generated header diffable, so a
    # prelude change shows up as the Python lines that changed.
    lines = src.split("\n", -1).map do |line|
      escaped = line.gsub("\\", "\\\\\\\\").gsub('"', '\\"')
      "    \"#{escaped}\\n\""
    end
    File.write(MP_PRELUDE_HEADER, <<~HEADER)
      /* Generated by "rake micropython:prelude" -- do not edit.
       * Source: #{MP_PRELUDE_DIR}/{#{MP_PRELUDE_FILES.join(',')}}
       *
       * The Python app framework, compiled into the firmware as source and
       * executed before every guest script. Frozen bytecode would be faster to
       * start but needs mpy-cross in the build; see report/phase3.md for what
       * the compile actually costs.
       */
      #pragma once

      static const char fmrb_mp_prelude_src[] =
      #{lines.join("\n")};
    HEADER
    puts "generated #{MP_PRELUDE_HEADER} (#{src.bytesize} bytes of Python)"
  end

  desc "Compile and run the host smoke test against #{MP_EMBED_DIR} (no docker)"
  task :smoke do
    unless File.exist?("#{MP_EMBED_DIR}/port/micropython_embed.h")
      abort "#{MP_EMBED_DIR} is missing. Run 'rake micropython:gen' first"
    end
    cc = ENV["CC"] || "cc"
    abort "#{cc} not found (install gcc or set CC)" unless system("which #{cc} > /dev/null 2>&1")
    srcs = Dir["#{MP_EMBED_DIR}/**/*.c"].sort + ["#{MP_PORT_DIR}/mpport.c", "#{MP_SMOKE_DIR}/main.c"]
    mkdir_p MP_SMOKE_BUILD
    sh "#{cc} #{MP_SMOKE_CFLAGS} -I #{MP_PORT_DIR} -I #{MP_EMBED_DIR} -I #{MP_EMBED_DIR}/port " \
       "#{srcs.join(' ')} -o #{MP_SMOKE_BIN} -lm"
    sh MP_SMOKE_BIN
  end

  desc "Remove the embed generation and smoke test intermediates"
  task :clean do
    rm_rf MP_GEN_BUILD
    rm_rf MP_SMOKE_BUILD
  end
end
