// Emits device-side encoded frames as hex so the Python codec can be compared
// byte for byte. Uses the real ble_framing.c and the exact frame layout from
// fmrb_debug_transport_ble.c's send().
//
// Build (from tool/debug/):
//   cc -I../../main/drivers/ble framing_vec.c ../../main/drivers/ble/ble_framing.c \
//      -o framing_vec
//
//   ./framing_vec hex <hexbody>   -> prints the encoded frame hex
//   ./framing_vec fuzz <count>    -> prints "<bodyhex> <framehex>" per line,
//                                    bodies generated by a deterministic LCG
//
// Cross-check against the Python codec:
//   ./framing_vec fuzz 2000 | python3 test_ble_framing_cross.py
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "ble_framing.h"

#define MAX_FRAME 4096
#define PLAIN_MAX (MAX_FRAME + 2 + 4)
#define MAX_ENC   (MAX_FRAME + 2 + 4 + ((MAX_FRAME + 6) / 254) + 2)

static uint8_t s_plain[PLAIN_MAX];
static uint8_t s_enc[MAX_ENC];

static int build_frame(const uint8_t *body, size_t len, size_t *out_len)
{
    if (len > MAX_FRAME) return -1;
    s_plain[0] = (uint8_t)(len >> 8);
    s_plain[1] = (uint8_t)len;
    memcpy(s_plain + 2, body, len);

    size_t plain_len = 2 + len;
    uint32_t crc = ble_framing_crc32(s_plain, plain_len);
    s_plain[plain_len++] = (uint8_t)(crc >> 24);
    s_plain[plain_len++] = (uint8_t)(crc >> 16);
    s_plain[plain_len++] = (uint8_t)(crc >> 8);
    s_plain[plain_len++] = (uint8_t)crc;

    size_t enc_len = ble_framing_cobs_encode(s_plain, plain_len, s_enc, sizeof(s_enc));
    if (enc_len == 0 || enc_len >= sizeof(s_enc)) return -2;
    s_enc[enc_len++] = 0x00;
    *out_len = enc_len;
    return 0;
}

static void print_hex(const uint8_t *p, size_t n)
{
    for (size_t i = 0; i < n; i++) printf("%02x", p[i]);
}

// Deterministic generator mirrored exactly in the Python side.
static uint32_t g_state;
static uint32_t next_rand(void)
{
    g_state = g_state * 1103515245u + 12345u;
    return (g_state >> 16) & 0x7FFF;
}

int main(int argc, char **argv)
{
    if (argc < 3) { fprintf(stderr, "usage: framing_vec hex <hexbody> | fuzz <count>\n"); return 2; }

    static uint8_t body[MAX_FRAME];

    if (strcmp(argv[1], "hex") == 0) {
        const char *h = argv[2];
        size_t len = strlen(h) / 2;
        if (len > MAX_FRAME) { fprintf(stderr, "body too long\n"); return 2; }
        for (size_t i = 0; i < len; i++) {
            unsigned v;
            sscanf(h + i * 2, "%2x", &v);
            body[i] = (uint8_t)v;
        }
        size_t enc_len;
        if (build_frame(body, len, &enc_len) != 0) { fprintf(stderr, "build failed\n"); return 1; }
        print_hex(s_enc, enc_len);
        printf("\n");
        return 0;
    }

    if (strcmp(argv[1], "fuzz") == 0) {
        int count = atoi(argv[2]);
        g_state = 987654321u;
        for (int i = 0; i < count; i++) {
            size_t len = next_rand() % (MAX_FRAME + 1);
            for (size_t j = 0; j < len; j++) body[j] = (uint8_t)(next_rand() & 0xFF);
            size_t enc_len;
            if (build_frame(body, len, &enc_len) != 0) { fprintf(stderr, "build failed at %d\n", i); return 1; }
            print_hex(body, len);
            printf(" ");
            print_hex(s_enc, enc_len);
            printf("\n");
        }
        return 0;
    }

    fprintf(stderr, "unknown mode\n");
    return 2;
}
