#!/usr/bin/env python3
"""Run BASIC screen golden cases inside the Linux simulation and diff the dump.

The same cases run much faster in the host runner (`rake basic:test`), which
compares the whole output. This script exists to prove the *device* path: the
interpreter writes its 28x24 shadow buffer, _SCRDUMP emits it through the log,
and the harness pulls it back out with a line filter (phase_b0_report sec 3.3).

It needs a running simulation stack (tools/dev_run_check.sh --keep at the
family-mruby root) and the debug daemon port (5555) the compose file exposes;
apps are launched over that port instead of by clicking the desktop launcher.

Usage:
    tools/basic_screen_check.py [case ...]      # default: every 2xx case
    tools/basic_screen_check.py --list
"""

import argparse
import os
import re
import shutil
import subprocess
import sys
import time

HERE = os.path.dirname(os.path.abspath(__file__))
CORE = os.path.normpath(os.path.join(HERE, ".."))
GOLDEN = os.path.join(CORE, "components", "basic", "test", "golden")
APP_DIR = os.path.join(CORE, "flash", "app", "demo")
APP_NAME = "_screencheck"
APP_BAS = os.path.join(APP_DIR, APP_NAME + ".app.bas")
APP_TOML = os.path.join(APP_DIR, APP_NAME + ".app.toml")
CONTAINER = "fmruby_core"

sys.path.insert(0, os.path.join(CORE, "tool", "debug"))

APP_TOML_BODY = """# Generated by tools/basic_screen_check.py; removed after the run.
app_handle_name = "{name}"
app_screen_name = "BASIC screen check"
""".format(name=APP_NAME)


def screen_lines(text):
    """Every SCRD dump line, in order."""
    return [m.group(0) for m in re.finditer(r"SCRD\|\d+\|.*", text)]


def expected_lines(case):
    with open(os.path.join(GOLDEN, case + ".expected")) as fp:
        return screen_lines(fp.read())


def docker_logs(since=None):
    cmd = ["docker", "logs"]
    if since is not None:
        cmd += ["--since", str(since)]
    cmd.append(CONTAINER)
    out = subprocess.run(cmd, capture_output=True, text=True)
    return out.stdout + out.stderr


def run_case(client, case, timeout=60.0):
    src = os.path.join(GOLDEN, case + ".bas")
    if not os.path.exists(src):
        return False, "no such case"
    want = expected_lines(case)
    if not want:
        return False, "case has no _SCRDUMP output"

    shutil.copyfile(src, APP_BAS)
    with open(APP_TOML, "w") as fp:
        fp.write(APP_TOML_BODY)

    # docker's --since only has second resolution, which is coarse enough for
    # one case's dump to leak into the next. Count what is already there and
    # look only at the lines that appear after the spawn.
    already = len(screen_lines(docker_logs()))
    try:
        client.spawn("/app/demo/" + APP_NAME + ".app.bas")
    except Exception as exc:  # noqa: BLE001 - report and continue with the next case
        return False, "spawn failed: %s" % exc

    # The dump ends with an END line carrying the body line count.
    deadline = time.time() + timeout
    got = []
    while time.time() < deadline:
        got = screen_lines(docker_logs())[already:]
        if got and got[-1].split("|")[-1].startswith("END"):
            break
        time.sleep(1.0)

    if got == want:
        return True, "%d dump lines" % len(got)

    detail = []
    for i in range(max(len(want), len(got))):
        w = want[i] if i < len(want) else "<missing>"
        g = got[i] if i < len(got) else "<missing>"
        if w != g:
            detail.append("    line %d\n      expected: %s\n      actual  : %s" % (i, w, g))
            if len(detail) >= 3:
                break
    return False, "dump differs\n" + "\n".join(detail)


def cleanup():
    for path in (APP_BAS, APP_TOML):
        if os.path.exists(path):
            os.remove(path)


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("cases", nargs="*")
    parser.add_argument("--host", default="127.0.0.1")
    parser.add_argument("--port", type=int, default=5555)
    parser.add_argument("--list", action="store_true", help="list the cases and exit")
    args = parser.parse_args()

    cases = args.cases
    if not cases:
        cases = sorted(
            os.path.splitext(f)[0]
            for f in os.listdir(GOLDEN)
            if f.endswith(".bas") and f.startswith("2")
        )
        # Only cases that dump the screen and need no key script: the
        # simulation cannot feed INKEY$ deterministically, so those stay with
        # the host runner.
        cases = [
            c for c in cases
            if expected_lines(c) and not os.path.exists(os.path.join(GOLDEN, c + ".keys"))
        ]
    if args.list:
        for case in cases:
            print(case)
        return 0

    from fmrb_dbg_client import FmrbDebugClient, TcpTransport  # noqa: E402

    client = FmrbDebugClient(TcpTransport(args.host, args.port))
    client.connect()

    passed = failed = 0
    try:
        for case in cases:
            ok, detail = run_case(client, case)
            print("%s %s (%s)" % ("PASS" if ok else "FAIL", case, detail))
            passed += ok
            failed += not ok
    finally:
        cleanup()
        client.close()

    print("---")
    print("screen (linux sim): %d passed, %d failed" % (passed, failed))
    return 1 if failed else 0


if __name__ == "__main__":
    sys.exit(main())
