#!/usr/bin/env python3
"""Generate the placeholder tile set for Family BASIC character table A.

Table A holds the built in animation characters (Mario, Lady, the enemies and
so on -- core_spec sec 12). Those are Nintendo's artwork, so this project
cannot ship them; what it ships is a placeholder set that keeps the *code
positions* meaningful and stays readable on screen, so DEF SPRITE and DEF MOVE
can be developed and tested. Real artwork is a separate job (00_common, open
question 2) and only changes this file's output.

The placeholders are procedural on purpose: 16x16 characters occupy four
consecutive codes (top left, top right, bottom left, bottom right), so each
tile draws the part of a framed box that its position in the quad calls for,
plus a body pattern derived from the quad number. A sprite therefore reads as
one box with a distinguishing pattern rather than four unrelated squares.

Usage:
    tools/gen_basic_tiles.py [output.c]
        default output: components/basic/assets/basic_tile_a.c
"""

import os
import sys

CELL = 8


def quad_frame(rows, part):
    """Draw the border segments this quadrant owns.

    part: 0 = top left, 1 = top right, 2 = bottom left, 3 = bottom right.
    """
    top = part in (0, 1)
    bottom = part in (2, 3)
    left = part in (0, 2)
    right = part in (1, 3)

    for y in range(CELL):
        for x in range(CELL):
            edge = (
                (top and y == 0)
                or (bottom and y == CELL - 1)
                or (left and x == 0)
                or (right and x == CELL - 1)
            )
            if edge:
                rows[y] |= 0x80 >> x


def body_pattern(rows, kind, part):
    """Fill the inside with a pattern that identifies the character."""
    for y in range(1, CELL - 1):
        for x in range(1, CELL - 1):
            on = False
            if kind == 0:
                on = (x + y) % 3 == 0            # diagonal hatch
            elif kind == 1:
                on = y % 2 == 0                  # horizontal bars
            elif kind == 2:
                on = x % 2 == 0                  # vertical bars
            elif kind == 3:
                on = (x // 2 + y // 2) % 2 == 0  # coarse checker
            elif kind == 4:
                on = 2 <= x <= 5 and 2 <= y <= 5  # centre block
            elif kind == 5:
                on = x == y or x + y == CELL - 1  # cross
            elif kind == 6:
                on = (x * y) % 5 == 0            # sparse dots
            else:
                on = False                        # hollow
            if on:
                rows[y] |= 0x80 >> x

    # A dot in the quadrant's own corner keeps the four tiles of a 16x16
    # character distinguishable when they are used on their own.
    corner_x = 1 if part in (0, 2) else CELL - 2
    corner_y = 1 if part in (0, 1) else CELL - 2
    rows[corner_y] |= 0x80 >> corner_x


def build():
    glyphs = []
    for code in range(256):
        rows = [0] * CELL
        quad = code // 4          # which 16x16 character this tile belongs to
        part = code % 4           # position inside it
        quad_frame(rows, part)
        body_pattern(rows, quad % 8, part)
        glyphs.append(rows)
    return glyphs


def emit_c(glyphs, path):
    lines = [
        "// Generated by tools/gen_basic_tiles.py -- do not edit by hand.",
        "//",
        "// Placeholder artwork for Family BASIC character table A (the built in",
        "// animation characters). Code positions follow core_spec sec 12; the shapes",
        "// are procedural stand ins for artwork this project cannot ship.",
        "// Bit 7 of each byte is the leftmost pixel.",
        "",
        '#include "basic_tile_a.h"',
        "",
        "const uint8_t basic_tile_a[256][8] = {",
    ]
    for code in range(256):
        rows = ", ".join("0x%02X" % v for v in glyphs[code])
        lines.append("    {%s},  // %d" % (rows, code))
    lines.append("};")
    lines.append("")
    with open(path, "w") as fp:
        fp.write("\n".join(lines))


def main():
    here = os.path.dirname(os.path.abspath(__file__))
    default = os.path.join(here, "..", "components", "basic", "assets", "basic_tile_a.c")
    out = sys.argv[1] if len(sys.argv) > 1 else os.path.normpath(default)
    emit_c(build(), out)
    print("wrote %s" % out)


if __name__ == "__main__":
    main()
