/*
 * The receiver for the minimal Spinel sample: an mruby task builds a Spinel
 * instance beside its own VM, calls the Spinel-compiled entry the way it would
 * call a C function, and tears the instance down. That works because an
 * instance is per-task state (fmrb_spinel_host.h) and mruby's mrb_state knows
 * nothing about it. See doc/spinel_aot/adding_a_spinel_gem.md.
 *
 * spinel/spinel_hello_kernel.rb is compiled as a Spinel ext program; its
 * generated header declares Init_spinel_hello() and the entry as a typed C
 * function (a String in, a String out). This file includes that header, so it
 * is compiled with the same flags as the generated program
 * (SPINEL_GEN_TU_FLAGS in main/CMakeLists.txt).
 *
 * No FMRB_..._SPINEL opt-out flag: this sample is Spinel-only, so it is always
 * compiled (there is no stub half).
 */
#include <stdint.h>
#include <string.h>

#include "spinel_hello_kernel.h"   /* generated by rake spinel:gen */
#include "spinel_hello_native.h"
#include "fmrb_app.h"
#include "fmrb_log.h"
#include "fmrb_mem.h"
#include "fmrb_spinel_host.h"

/* Placement for this file's statics. None of them is on a hot path, and
   internal DRAM is the scarce resource, so on ESP32 they live in PSRAM; on
   the Linux build it is plain BSS. Same shape as FMRB_SPX_BSS_ATTR. */
#ifdef CONFIG_IDF_TARGET_LINUX
#define SH_BSS_ATTR
#else
#include "esp_attr.h"
#define SH_BSS_ATTR EXT_RAM_BSS_ATTR
#endif

static const char *TAG = "spinel_hello";

/* The greeting itself is tiny, but a Spinel instance needs a baseline heap for
   its own bootstrap (class table, interned symbols, string heap) before any
   Ruby runs, and that baseline grows with the runtime. 128 KB is what the
   raycast gem uses, and that one has kept working. */
#define SH_POOL_BYTES (128 * 1024)
#define SH_OUT_MAX    64
#define SH_NAME_MAX   48

/* The instance and the app task that owns it (fmrb_spinel_host.h). Zeroed
   storage (a BSS section); name and pool_free are filled in by begin(). */
static void sh_pool_free(void *p) { fmrb_sys_free(p); }
SH_BSS_ATTR static fmrb_spinel_gem_t s_gem;

/* The greeting, copied out of the instance's heap. Valid until the next
   run(). */
SH_BSS_ATTR static char  s_out[SH_OUT_MAX];

/* Every call into the program goes through Init_spinel_hello_try: a Ruby
   raise that escapes it would otherwise end the whole firmware. */
typedef struct {
    const char *name;
    const char *out;
} sh_call_t;

static void sh_init(void *p)  { (void)p; Init_spinel_hello(); }
static void sh_greet(void *p) { sh_call_t *c = (sh_call_t *)p; c->out = sp_SpinelHelloKernel_s_greet(c->name); }

static int sh_try(void (*fn)(void *), void *arg, const char *what)
{
    const char *cls = NULL, *msg = NULL;
    if (Init_spinel_hello_try(fn, arg, &cls, &msg)) {
        FMRB_LOGE(TAG, "%s raised %s: %s", what, cls ? cls : "?", msg ? msg : "");
        return -1;
    }
    return 0;
}

int spinel_hello_available(void)
{
    return 1;
}

int spinel_hello_begin(void)
{
    void *me = (void *)fmrb_task_get_current();
    fmrb_app_task_context_t *app = fmrb_current();
    s_gem.name = "spinel_hello";     /* constants: harmless if two tasks race */
    s_gem.pool_free = sh_pool_free;
    int claim = fmrb_spinel_gem_claim(&s_gem, me, app ? (int)app->app_id : -1,
                                      app ? app->app_name : "?");
    if (claim == FMRB_SPINEL_GEM_MINE) {
        return 0;
    }
    if (claim == FMRB_SPINEL_GEM_BUSY) {
        return SPINEL_HELLO_BUSY;
    }
    s_gem.pool = fmrb_sys_malloc(SH_POOL_BYTES);
    if (!s_gem.pool) {
        FMRB_LOGE(TAG, "no memory for the Spinel Hello pool (%d bytes)", SH_POOL_BYTES);
        fmrb_spinel_gem_release(&s_gem);
        return -2;
    }
    size_t threshold = SH_POOL_BYTES / 32;
    void *est = fmrb_spinel_instance_begin(s_gem.pool, SH_POOL_BYTES, threshold, threshold);
    if (!est) {
        FMRB_LOGE(TAG, "could not create the Spinel Hello instance (pool %d bytes: "
                       "too small for the runtime's own bootstrap?)", SH_POOL_BYTES);
        fmrb_sys_free(s_gem.pool);
        fmrb_spinel_gem_release(&s_gem);
        return -3;
    }
    s_gem.est = est;
    if (sh_try(sh_init, NULL, "init") != 0) {
        fmrb_spinel_instance_end(est);
        fmrb_sys_free(s_gem.pool);
        fmrb_spinel_gem_release(&s_gem);
        return -4;
    }
    FMRB_LOGI(TAG, "Spinel Hello instance up (%d bytes)", SH_POOL_BYTES);
    return 0;
}

void spinel_hello_note_fallback(const char *backend)
{
    fmrb_app_task_context_t *app = fmrb_current();
    FMRB_LOGI(TAG, "[%s] the Spinel Hello instance belongs to %s (pid %d); "
                   "this app runs on the %s backend instead",
              app ? app->app_name : "?", s_gem.owner_app, s_gem.owner_pid,
              backend ? backend : "?");
}

const char *spinel_hello_run(const char *name, int name_len, int *len_out)
{
    if (len_out) *len_out = 0;
    if (!fmrb_spinel_gem_is_open_on(&s_gem, (void *)fmrb_task_get_current())) {
        return NULL;
    }
    if (name_len < 0) name_len = 0;
    if (name_len > SH_NAME_MAX) name_len = SH_NAME_MAX;
    /* A Spinel String carries its length in a header in front of the bytes,
       so the argument is built on the instance's heap, not passed as a C
       buffer. */
    sh_call_t c = { sp_str_from_bytes(name ? name : "", (size_t)name_len), NULL };
    if (sh_try(sh_greet, &c, "greet") != 0 || !c.out) {
        return NULL;
    }
    int len = (int)sp_str_byte_len(c.out);
    if (len > SH_OUT_MAX) len = SH_OUT_MAX;
    memcpy(s_out, c.out, (size_t)len);
    if (len_out) *len_out = len;
    return s_out;
}

void spinel_hello_end(void)
{
    /* Only the owner tears the instance down: the gem's final hook calls this
       from every mruby app's VM as it closes, and an app that never owned the
       instance must not take it from the one that does. */
    if (!fmrb_spinel_gem_is_open_on(&s_gem, (void *)fmrb_task_get_current())) {
        return;
    }
    fmrb_spinel_instance_end(s_gem.est);
    fmrb_sys_free(s_gem.pool);
    fmrb_spinel_gem_release(&s_gem);
}
