/**
 * @file basic_tile_a.h
 * @brief Family BASIC character table A (sprite / animation tiles)
 *
 * Generated by tools/gen_basic_tiles.py. Placeholder artwork: the code
 * positions follow the spec (core_spec sec 12) so DEF SPRITE and DEF MOVE
 * behave correctly, but the shapes are stand ins for artwork this project
 * cannot ship. Bit 7 of each row byte is the leftmost pixel.
 */

#pragma once

#include <stdint.h>

#ifdef __cplusplus
extern "C" {
#endif

/// Sprite tile bitmaps, indexed by table A character code.
extern const uint16_t basic_tile_a[256][8];

#ifdef __cplusplus
}
#endif
