/**
 * @file basic_font8.h
 * @brief FMRuby BASIC 8x8 text font
 *
 * Generated by tools/gen_basic_font.py. Code positions follow the Family
 * BASIC character table (core_spec sec 12); the shapes are original artwork
 * for this project (Family BASIC's own character generator is copyrighted).
 * Bit 7 of each row byte is the leftmost pixel.
 */

#pragma once

#include <stdint.h>

#ifdef __cplusplus
extern "C" {
#endif

/// Glyph bitmaps, indexed by Family BASIC character code.
extern const uint8_t basic_font8[256][8];

#ifdef __cplusplus
}
#endif
