/**
 * @file basic_tile_a.h
 * @brief Family BASIC character table A (sprite / animation tiles)
 *
 * Generated by tool/basic/gen_basic_tiles.rb. The code positions follow the
 * spec (core_spec sec 12) so DEF SPRITE and DEF MOVE animate the role a
 * program asks for; the artwork is this project's own cast, drawn in the
 * generator. Two bits per pixel, the leftmost pixel being the top pair of
 * each row.
 */

#pragma once

#include <stdint.h>

#ifdef __cplusplus
extern "C" {
#endif

/// Sprite tile bitmaps, indexed by table A character code.
extern const uint16_t basic_tile_a[256][8];

#ifdef __cplusplus
}
#endif
