app_handle_name = "flappy_demo"
app_screen_name = "FlappyDemo"
app_screen_name_ja = "フラッピーゲーム"
default_window_mode = "window"
default_window_width = 200
default_window_height = 150
default_window_pos_x = 10
default_window_pos_y = 15
