# Shooter - a formation shoot 'em up.
#
# Controls
#   Keyboard: arrows move, Space fires (hold to keep firing), Enter restarts
#   Gamepad:  D-pad / left stick move, Circle fires, Cross restarts, Start quits
#
# The artwork is a set of BMPs under /usr/share/sprites/shooter, the same
# route flappy.rb uses: the files are transferred to the graphics side once
# (sync_file, which skips the copy when the CRC already matches) and decoded
# there by SpriteImage#load_bmp. The editable source is the pixel art in
# tool/gen_shooter_sprites.rb -- edit it there and re-run "rake sprites".
#
# Enemies arrive as a block: each one flies in from off screen along an arc,
# settles into its slot, sways with the rest of the formation, and now and
# then one peels off to dive at the player. Clearing the block starts the next
# wave, which dives more often and drops in faster.
#
# Sound is the APU (FmrbAudio#note_on / #note_off): a falling pulse blip when
# the player fires, a noise burst when something is hit, and a longer low
# noise plus a triangle thud when the player is hit. Every effect is started
# with note_on and finished by tick_sfx counting down to note_off, which is
# the pattern rpg_demo uses; @sfx_seq stops a finished effect from silencing
# the one that replaced it on the same channel.

class ShooterApp < FmrbApp
  # ---- Palette (RGB332) ----
  COL_HUD_BG   = 0x00
  COL_HUD_LINE = 0x49
  COL_TEXT     = 0xFF
  COL_SKY      = 0x00
  COL_STAR_HI  = 0xFF
  COL_STAR_MID = 0xB6
  COL_STAR_LO  = 0x49
  COL_PLANET   = 0x21
  COL_PLANET_R = 0x4A
  # The glow along the horizon. The same blue-violet as the planet's lit rim,
  # so the line reads as that light reaching the horizon -- as pure green it
  # read as a stray bar across the bottom of the screen.
  COL_HORIZON  = 0x4A
  COL_OVER_BG  = 0x40

  # ---- Artwork ----
  # Generated by tool/gen_shooter_sprites.rb. The two enemy types are the same
  # drawing in two palettes, so the colour is already baked into the file.
  SPRITE_SRC = "/usr/share/sprites/shooter"
  SPRITE_CACHE = "/cache/app/shooter"
  SPRITE_FILES = ["player_a.bmp", "player_b.bmp",
                  "enemy1_a.bmp", "enemy1_b.bmp",
                  "enemy2_a.bmp", "enemy2_b.bmp",
                  "bullet.bmp", "burst_a.bmp", "burst_b.bmp"]

  PLAYER_W = 16
  PLAYER_H = 16
  ENEMY_W  = 16
  ENEMY_H  = 12
  BULLET_W = 4
  BULLET_H = 6
  BURST_W  = 16
  BURST_H  = 16

  # ---- Layout ----
  HUD_H = 12
  FORM_COLS = 6
  FORM_ROWS = 3
  CELL_W = 28
  CELL_H = 22
  FORM_TOP = HUD_H + 16
  SWAY_MAX = 12
  SWAY_EVERY = 3          # ticks between one pixel of formation drift

  # ---- Play ----
  MAX_BULLETS = 6
  MAX_BURSTS  = 4
  PLAYER_SPEED = 4
  BULLET_SPEED = 9
  SHOT_COOLDOWN = 4       # ticks between shots while the fire key is held
  ENTER_TICKS = 26        # length of the fly-in path
  DIVE_TURN = 18          # ticks a diver takes to line up with the player
  DIVE_SPEED = 5
  INVULN_TICKS = 30
  START_LIVES = 3
  TICK_MS = 50

  # Quarter of a sine, scaled to 127. Used for the fly-in arc and the wiggle
  # of a diving enemy; a table keeps the paths curved without floating point.
  SIN16 = [0, 49, 90, 118, 127, 118, 90, 49,
           0, -49, -90, -118, -127, -118, -90, -49]

  # ---- APU ----
  CH_PULSE1 = 0
  CH_PULSE2 = 1
  CH_TRI    = 2
  CH_NOISE  = 3

  def initialize
    super()
    @input = {}
    @fire_held = false
    @restart_pressed = false
  end

  def on_create
    Log.info("Shooter on_create")
    FmrbApp.set_cursor_visible(false)
    @play_h = @user_area_height
    setup_audio
    setup_sprites
    reset_game
  end

  def on_destroy
    silence_audio
    destroy_sprites
    FmrbApp.set_cursor_visible(true)
    Log.info("Shooter destroyed")
  end

  # ---- Setup -----------------------------------------------------------

  def setup_audio
    # picoruby has no defined?, so just try it: the rescue covers both a
    # missing FmrbAudio and an audio side that will not start.
    @audio = FmrbAudio.new(self)
    @sfx_seq = [0, 0, 0, 0]
    @sfx_pending = []
  rescue => e
    Log.warn("Audio unavailable: #{e.message}")
    @audio = nil
    @sfx_seq = [0, 0, 0, 0]
    @sfx_pending = []
  end

  # Show progress while the files go across: on a cold cache this is nine
  # transfers and the screen would otherwise sit blank.
  def transfer_sprites
    ox = @user_area_x0
    oy = @user_area_y0
    i = 0
    while i < SPRITE_FILES.length
      name = SPRITE_FILES[i]
      @gfx.fill_rect(ox, oy, @user_area_width, @play_h, COL_SKY)
      @gfx.draw_text(ox + 8, oy + 10, "Loading sprites...", COL_TEXT, COL_SKY)
      @gfx.draw_text(ox + 8, oy + 24,
                     "#{name} (#{i + 1}/#{SPRITE_FILES.length})", 0x1F, COL_SKY)
      @gfx.present
      @gfx.sync_file("#{SPRITE_SRC}/#{name}", dest: "#{SPRITE_CACHE}/#{name}")
      i += 1
    end
    Log.info("Shooter: sprites transferred")
  end

  def load_sprite_image(name, w, h)
    img = SpriteImage.new(@gfx, width: w, height: h,
                          transparent_color: 0, use_transparent: true)
    img.load_bmp("#{SPRITE_CACHE}/#{name}")
    img
  end

  def setup_sprites
    transfer_sprites
    @player_imgs = [load_sprite_image("player_a.bmp", PLAYER_W, PLAYER_H),
                    load_sprite_image("player_b.bmp", PLAYER_W, PLAYER_H)]
    @enemy_imgs = [
      [load_sprite_image("enemy1_a.bmp", ENEMY_W, ENEMY_H),
       load_sprite_image("enemy1_b.bmp", ENEMY_W, ENEMY_H)],
      [load_sprite_image("enemy2_a.bmp", ENEMY_W, ENEMY_H),
       load_sprite_image("enemy2_b.bmp", ENEMY_W, ENEMY_H)],
    ]
    @bullet_img = load_sprite_image("bullet.bmp", BULLET_W, BULLET_H)
    @burst_imgs = [load_sprite_image("burst_a.bmp", BURST_W, BURST_H),
                   load_sprite_image("burst_b.bmp", BURST_W, BURST_H)]

    @player_sprite = SpriteInstance.new(@gfx, @player_imgs, x: 0, y: 0, z: 3)
    @player_sprite.visible = false

    @bullet_pool = []
    i = 0
    while i < MAX_BULLETS
      s = SpriteInstance.new(@gfx, @bullet_img, x: 0, y: 0, z: 2)
      s.visible = false
      @bullet_pool << s
      i += 1
    end

    # One instance per formation slot: the block never holds more than that,
    # so the pool never has to grow or shuffle.
    @enemy_sprites = []
    i = 0
    while i < FORM_COLS * FORM_ROWS
      row = i / FORM_COLS
      s = SpriteInstance.new(@gfx, @enemy_imgs[row == 0 ? 1 : 0], x: 0, y: 0, z: 2)
      s.visible = false
      @enemy_sprites << s
      i += 1
    end

    @burst_pool = []
    i = 0
    while i < MAX_BURSTS
      s = SpriteInstance.new(@gfx, @burst_imgs, x: 0, y: 0, z: 4)
      s.visible = false
      @burst_pool << s
      i += 1
    end
  end

  def destroy_sprites
    @bullet_pool.each { |s| s.destroy } if @bullet_pool
    @enemy_sprites.each { |s| s.destroy } if @enemy_sprites
    @burst_pool.each { |s| s.destroy } if @burst_pool
    @player_sprite.destroy if @player_sprite
    @player_imgs.each { |i| i.destroy } if @player_imgs
    @enemy_imgs.each { |pair| pair.each { |i| i.destroy } } if @enemy_imgs
    @burst_imgs.each { |i| i.destroy } if @burst_imgs
    @bullet_img.destroy if @bullet_img
  end

  # ---- Game state ------------------------------------------------------

  def reset_game
    @score = 0
    @lives = START_LIVES
    @wave = 1
    @game_over = false
    @tick = 0
    @sway = 0
    @sway_dir = 1
    @invuln = 0
    @shot_timer = 0
    @dive_timer = 60
    @bullets = []
    @bursts = []
    @free_bullets = @bullet_pool.dup
    @free_bursts = @burst_pool.dup
    @input = {}
    @fire_held = false

    @player_x = @user_area_width / 2
    @player_y = @play_h - PLAYER_H - 10

    start_wave
    draw_background
    draw_hud
    @player_sprite.visible = true
    move_player_sprite
    @gfx.present
  end

  def start_wave
    @enemies = []
    idx = 0
    while idx < FORM_COLS * FORM_ROWS
      col = idx % FORM_COLS
      row = idx / FORM_COLS
      sprite = @enemy_sprites[idx]
      sprite.visible = true
      # Odd columns come in from the right, even ones from the left, and each
      # one waits a little longer than the last so the block streams in.
      from_left = (col % 2) == 0
      e = {
        sprite: sprite, col: col, row: row,
        state: :enter, t: -(col * 3 + row * 5),
        sx: from_left ? -ENEMY_W - 8 : @user_area_width + 8,
        sy: HUD_H + 4 + row * 6,
        x: 0, y: -40, tx: 0, dive_x: 0, dive_y: 0,
      }
      # Park it off screen straight away: the sprite is visible from here on,
      # and without this it would show at its position from the last wave
      # until the first update moved it.
      sprite.move(@user_area_x0 + e[:x], @user_area_y0 + e[:y])
      @enemies << e
      idx += 1
    end
    @dive_timer = 70
  end

  # ---- Input -----------------------------------------------------------

  def on_event(ev)
    super(ev)
    case ev[:type]
    when :key_down
      # Arrow keys carry no character, so they come in as scancodes (HID
      # usage ids, which is what FmrbConst::KEY_* holds).
      case ev[:scancode]
      when FmrbConst::KEY_LEFT  then @input[:left]  = true
      when FmrbConst::KEY_RIGHT then @input[:right] = true
      when FmrbConst::KEY_UP    then @input[:up]    = true
      when FmrbConst::KEY_DOWN  then @input[:down]  = true
      end
      c = ev[:character]
      @fire_held = true if c == 32
      @restart_pressed = true if c == 10 || c == 13
    when :key_up
      case ev[:scancode]
      when FmrbConst::KEY_LEFT  then @input[:left]  = false
      when FmrbConst::KEY_RIGHT then @input[:right] = false
      when FmrbConst::KEY_UP    then @input[:up]    = false
      when FmrbConst::KEY_DOWN  then @input[:down]  = false
      end
      @fire_held = false if ev[:character] == 32
    when :gamepad_down
      case ev[:button]
      when FmrbConst::GP_UP     then @input[:up]    = true
      when FmrbConst::GP_DOWN   then @input[:down]  = true
      when FmrbConst::GP_LEFT   then @input[:left]  = true
      when FmrbConst::GP_RIGHT  then @input[:right] = true
      when FmrbConst::GP_CIRCLE then @fire_held = true
      when FmrbConst::GP_CROSS  then @restart_pressed = true
      when FmrbConst::GP_START  then stop
      end
    when :gamepad_up
      case ev[:button]
      when FmrbConst::GP_UP     then @input[:up]    = false
      when FmrbConst::GP_DOWN   then @input[:down]  = false
      when FmrbConst::GP_LEFT   then @input[:left]  = false
      when FmrbConst::GP_RIGHT  then @input[:right] = false
      when FmrbConst::GP_CIRCLE then @fire_held = false
      end
    when :gamepad_axis
      if ev[:axis] == FmrbConst::GP_AXIS_LX
        v = ev[:value]
        @input[:left]  = v < -30
        @input[:right] = v > 30
      elsif ev[:axis] == FmrbConst::GP_AXIS_LY
        v = ev[:value]
        @input[:up]   = v < -30
        @input[:down] = v > 30
      end
    end
  end

  # ---- Frame -----------------------------------------------------------

  def on_update
    if @game_over
      if @restart_pressed
        @restart_pressed = false
        reset_game
      end
      return TICK_MS
    end
    @restart_pressed = false
    @tick += 1

    update_player
    update_bullets
    update_formation
    update_enemies
    update_bursts
    check_hits
    tick_sfx
    return TICK_MS if @game_over

    if @enemies.empty?
      @wave += 1
      @score += 500
      sfx_wave
      start_wave
      draw_hud
    end

    @gfx.present
    TICK_MS
  end

  def update_player
    @player_x -= PLAYER_SPEED if @input[:left]
    @player_x += PLAYER_SPEED if @input[:right]
    @player_y -= PLAYER_SPEED if @input[:up]
    @player_y += PLAYER_SPEED if @input[:down]

    @player_x = 0 if @player_x < 0
    max_x = @user_area_width - PLAYER_W
    @player_x = max_x if @player_x > max_x
    # Kept below the block: only divers are checked against the player, so
    # letting the ship wander up into the formation would look wrong.
    min_y = FORM_TOP + FORM_ROWS * CELL_H + 16
    @player_y = min_y if @player_y < min_y
    max_y = @play_h - PLAYER_H
    @player_y = max_y if @player_y > max_y

    # Exhaust flicker, and the blink that shows the player is still safe
    # after being hit.
    @player_sprite.frame = (@tick % 4 < 2) ? 0 : 1
    if @invuln > 0
      @invuln -= 1
      @player_sprite.visible = (@invuln % 4) < 2
      @player_sprite.visible = true if @invuln == 0
    end
    move_player_sprite

    @shot_timer -= 1 if @shot_timer > 0
    if @fire_held && @shot_timer == 0
      fire_bullet
      @shot_timer = SHOT_COOLDOWN
    end
  end

  def move_player_sprite
    @player_sprite.move(@user_area_x0 + @player_x, @user_area_y0 + @player_y)
  end

  def fire_bullet
    return if @free_bullets.empty?
    s = @free_bullets.pop
    x = @player_x + PLAYER_W / 2 - BULLET_W / 2
    y = @player_y - BULLET_H
    s.visible = true
    s.move(@user_area_x0 + x, @user_area_y0 + y)
    @bullets << { x: x, y: y, sprite: s }
    sfx_shot
  end

  def update_bullets
    i = @bullets.length - 1
    while i >= 0
      b = @bullets[i]
      b[:y] -= BULLET_SPEED
      if b[:y] < HUD_H - BULLET_H
        release_bullet(i)
      else
        b[:sprite].move(@user_area_x0 + b[:x], @user_area_y0 + b[:y])
      end
      i -= 1
    end
  end

  def release_bullet(i)
    b = @bullets[i]
    b[:sprite].visible = false
    @free_bullets.push(b[:sprite])
    @bullets.delete_at(i)
  end

  # The whole block drifts sideways together.
  def update_formation
    return unless (@tick % SWAY_EVERY) == 0
    @sway += @sway_dir
    if @sway >= SWAY_MAX
      @sway = SWAY_MAX
      @sway_dir = -1
    elsif @sway <= -SWAY_MAX
      @sway = -SWAY_MAX
      @sway_dir = 1
    end
  end

  def form_x0
    (@user_area_width - FORM_COLS * CELL_W) / 2 + (CELL_W - ENEMY_W) / 2
  end

  def slot_x(col); form_x0 + col * CELL_W + @sway; end
  def slot_y(row); FORM_TOP + row * CELL_H; end

  def update_enemies
    @dive_timer -= 1
    launch_dive if @dive_timer <= 0

    i = 0
    n = @enemies.length
    while i < n
      e = @enemies[i]
      case e[:state]
      when :enter then step_enter(e)
      when :form  then step_form(e)
      else             step_dive(e)
      end
      e[:sprite].move(@user_area_x0 + e[:x], @user_area_y0 + e[:y])
      i += 1
    end
    # Wing beat, shared by the whole block so it reads as one swarm.
    frame = (@tick % 8 < 4) ? 0 : 1
    if frame != @enemy_frame
      @enemy_frame = frame
      i = 0
      while i < n
        @enemies[i][:sprite].frame = frame
        i += 1
      end
    end
  end

  # Fly in from off screen to the slot, bulging along the way so the path is
  # an arc rather than a straight line.
  def step_enter(e)
    e[:t] += 1
    return if e[:t] < 0
    if e[:t] >= ENTER_TICKS
      e[:state] = :form
      step_form(e)
      return
    end
    tx = slot_x(e[:col])
    ty = slot_y(e[:row])
    p = e[:t]
    e[:x] = e[:sx] + (tx - e[:sx]) * p / ENTER_TICKS
    e[:y] = e[:sy] + (ty - e[:sy]) * p / ENTER_TICKS + SIN16[p * 8 / ENTER_TICKS] * 26 / 127
  end

  def step_form(e)
    e[:x] = slot_x(e[:col])
    e[:y] = slot_y(e[:row])
  end

  # Dive: swing toward where the player was, wiggling, then run off the
  # bottom and come back round to the slot.
  def step_dive(e)
    e[:t] += 1
    p = e[:t]
    turn = p < DIVE_TURN ? p : DIVE_TURN
    base = e[:dive_x] + (e[:tx] - e[:dive_x]) * turn / DIVE_TURN
    e[:x] = base + SIN16[p % 16] * 14 / 127
    e[:y] = e[:dive_y] + p * DIVE_SPEED
    if e[:y] > @play_h + ENEMY_H
      e[:state] = :enter
      e[:t] = 0
      e[:sx] = e[:x]
      e[:sy] = -ENEMY_H
    end
  end

  def launch_dive
    # Pick a settled enemy from the lowest row that still has one: the block
    # empties from the bottom, which is what makes it read as a formation.
    pick = nil
    i = @enemies.length - 1
    while i >= 0
      e = @enemies[i]
      if e[:state] == :form && (pick.nil? || e[:row] > pick[:row])
        pick = e
      end
      i -= 1
    end
    @dive_timer = 70 - @wave * 6
    @dive_timer = 18 if @dive_timer < 18
    return unless pick
    pick[:state] = :dive
    pick[:t] = 0
    pick[:dive_x] = pick[:x]
    pick[:dive_y] = pick[:y]
    pick[:tx] = @player_x
  end

  # ---- Hits ------------------------------------------------------------

  def check_hits
    bi = @bullets.length - 1
    while bi >= 0
      b = @bullets[bi]
      ei = @enemies.length - 1
      hit = -1
      while ei >= 0
        e = @enemies[ei]
        if e[:state] != :enter || e[:t] >= 0
          if overlap?(b[:x], b[:y], BULLET_W, BULLET_H,
                      e[:x], e[:y], ENEMY_W, ENEMY_H)
            hit = ei
            break
          end
        end
        ei -= 1
      end
      if hit >= 0
        e = @enemies[hit]
        spawn_burst(e[:x], e[:y] - 2)
        e[:sprite].visible = false
        @enemies.delete_at(hit)
        release_bullet(bi)
        @score += (e[:state] == :dive) ? 200 : 100
        sfx_hit
        draw_hud
      end
      bi -= 1
    end

    return if @invuln > 0
    i = 0
    n = @enemies.length
    while i < n
      e = @enemies[i]
      if e[:state] == :dive &&
         overlap?(@player_x + 2, @player_y + 2, PLAYER_W - 4, PLAYER_H - 4,
                  e[:x] + 2, e[:y] + 2, ENEMY_W - 4, ENEMY_H - 4)
        player_hit
        return
      end
      i += 1
    end
  end

  def overlap?(x1, y1, w1, h1, x2, y2, w2, h2)
    !(x1 + w1 <= x2 || x2 + w2 <= x1 || y1 + h1 <= y2 || y2 + h2 <= y1)
  end

  def player_hit
    spawn_burst(@player_x, @player_y)
    sfx_player_hit
    @lives -= 1
    if @lives <= 0
      trigger_game_over
      return
    end
    @invuln = INVULN_TICKS
    @player_x = @user_area_width / 2
    @player_y = @play_h - PLAYER_H - 10
    # Send the divers home rather than leaving them on top of the respawn.
    i = 0
    n = @enemies.length
    while i < n
      e = @enemies[i]
      if e[:state] == :dive
        e[:state] = :enter
        e[:t] = 0
        e[:sx] = e[:x]
        e[:sy] = e[:y]
      end
      i += 1
    end
    draw_hud
  end

  def spawn_burst(x, y)
    return if @free_bursts.empty?
    s = @free_bursts.pop
    s.frame = 0
    s.visible = true
    s.move(@user_area_x0 + x, @user_area_y0 + y)
    @bursts << { sprite: s, t: 0 }
  end

  def update_bursts
    i = @bursts.length - 1
    while i >= 0
      b = @bursts[i]
      b[:t] += 1
      if b[:t] >= 6
        b[:sprite].visible = false
        @free_bursts.push(b[:sprite])
        @bursts.delete_at(i)
      elsif b[:t] == 3
        b[:sprite].frame = 1
      end
      i -= 1
    end
  end

  def trigger_game_over
    @game_over = true
    @player_sprite.visible = false
    i = 0
    while i < @enemies.length
      @enemies[i][:sprite].visible = false
      i += 1
    end
    @bullets.each { |b| b[:sprite].visible = false }
    @bursts.each { |b| b[:sprite].visible = false }
    @bullets = []
    @bursts = []
    @free_bullets = @bullet_pool.dup
    @free_bursts = @burst_pool.dup
    silence_audio
    draw_hud
    draw_game_over
    @gfx.present
  end

  # ---- Sound -----------------------------------------------------------

  # Each effect claims its channel with a new sequence number, so the
  # note_off queued by the previous effect cannot cut this one short.
  def sfx_begin(ch)
    @sfx_seq[ch] = @sfx_seq[ch] + 1
    @sfx_seq[ch]
  end

  def sfx_shot
    return unless @audio
    g = sfx_begin(CH_PULSE2)
    @audio.note_on(CH_PULSE2, 1500, 5, 2, 0)
    @sfx_pending << { ch: CH_PULSE2, gen: g, t: 1, freq: 950, vol: 4, duty: 2 }
    @sfx_pending << { ch: CH_PULSE2, gen: g, t: 2, freq: nil }
  end

  def sfx_hit
    return unless @audio
    g = sfx_begin(CH_NOISE)
    @audio.note_on(CH_NOISE, 5, 10, 0, 0)
    @sfx_pending << { ch: CH_NOISE, gen: g, t: 1, freq: 8, vol: 7, duty: 0 }
    @sfx_pending << { ch: CH_NOISE, gen: g, t: 3, freq: nil }
  end

  def sfx_player_hit
    return unless @audio
    g = sfx_begin(CH_NOISE)
    @audio.note_on(CH_NOISE, 11, 13, 0, 0)
    @sfx_pending << { ch: CH_NOISE, gen: g, t: 3, freq: 14, vol: 9, duty: 0 }
    @sfx_pending << { ch: CH_NOISE, gen: g, t: 8, freq: nil }
    gt = sfx_begin(CH_TRI)
    @audio.note_on(CH_TRI, 100, 0, 0, 0)
    @sfx_pending << { ch: CH_TRI, gen: gt, t: 8, freq: nil }
  end

  def sfx_wave
    return unless @audio
    g = sfx_begin(CH_PULSE1)
    @audio.note_on(CH_PULSE1, 660, 6, 2, 0)
    @sfx_pending << { ch: CH_PULSE1, gen: g, t: 3, freq: 880, vol: 6, duty: 2 }
    @sfx_pending << { ch: CH_PULSE1, gen: g, t: 6, freq: 1320, vol: 6, duty: 2 }
    @sfx_pending << { ch: CH_PULSE1, gen: g, t: 10, freq: nil }
  end

  def tick_sfx
    return unless @audio
    i = @sfx_pending.length - 1
    while i >= 0
      e = @sfx_pending[i]
      e[:t] -= 1
      if e[:t] <= 0
        if @sfx_seq[e[:ch]] == e[:gen]
          if e[:freq]
            @audio.note_on(e[:ch], e[:freq], e[:vol], e[:duty], 0)
          else
            @audio.note_off(e[:ch])
          end
        end
        @sfx_pending.delete_at(i)
      end
      i -= 1
    end
  end

  def silence_audio
    return unless @audio
    ch = 0
    while ch < 4
      @audio.note_off(ch)
      ch += 1
    end
    @sfx_pending = []
  end

  # ---- Drawing ---------------------------------------------------------

  # Drawn once per game: the sprites are composited over it on every present,
  # so nothing here is repainted per frame.
  def draw_background
    ox = @user_area_x0
    oy = @user_area_y0
    w = @user_area_width
    h = @play_h
    @gfx.fill_rect(ox, oy, w, h, COL_SKY)

    i = 0
    while i < 90
      sx = ox + (RNG.random_int % w)
      sy = oy + HUD_H + (RNG.random_int % (h - HUD_H))
      r = RNG.random_int % 10
      color = r < 2 ? COL_STAR_HI : (r < 5 ? COL_STAR_MID : COL_STAR_LO)
      @gfx.set_pixel(sx, sy, color)
      i += 1
    end

    # A planet rising at the bottom left, and the glow along the horizon.
    cx = ox + w / 5
    cy = oy + h + 46
    @gfx.fill_circle(cx, cy, 78, COL_PLANET)
    @gfx.draw_circle(cx, cy, 78, COL_PLANET_R)
    @gfx.fill_rect(ox, oy + h - 2, w, 2, COL_HORIZON)

    draw_window_frame
  end

  def draw_hud
    ox = @user_area_x0
    oy = @user_area_y0
    w = @user_area_width
    @gfx.fill_rect(ox, oy, w, HUD_H, COL_HUD_BG)
    @gfx.fill_rect(ox, oy + HUD_H - 1, w, 1, COL_HUD_LINE)
    @gfx.draw_text(ox + 2, oy + 2, sprintf("SCORE %06d", @score), COL_TEXT, COL_HUD_BG)
    @gfx.draw_text(ox + w / 2 - 18, oy + 2, sprintf("WAVE %02d", @wave), COL_TEXT, COL_HUD_BG)
    # Lives as little ships rather than a number.
    lx = ox + w - 8
    i = 0
    while i < @lives - 1
      @gfx.fill_triangle(lx, oy + 3, lx - 4, oy + 9, lx + 4, oy + 9, 0x1F)
      lx -= 11
      i += 1
    end
  end

  def draw_game_over
    ox = @user_area_x0
    oy = @user_area_y0
    cx = ox + @user_area_width / 2
    cy = oy + @play_h / 2
    @gfx.fill_rect(cx - 62, cy - 22, 124, 46, COL_OVER_BG)
    @gfx.fill_rect(cx - 62, cy - 22, 124, 1, COL_TEXT)
    @gfx.fill_rect(cx - 62, cy + 23, 124, 1, COL_TEXT)
    @gfx.draw_text(cx - 27, cy - 15, "GAME OVER", COL_TEXT, COL_OVER_BG)
    @gfx.draw_text(cx - 45, cy - 1, sprintf("SCORE %06d", @score), COL_TEXT, COL_OVER_BG)
    @gfx.draw_text(cx - 57, cy + 13, "ENTER retry  Ctrl-Q quit", COL_TEXT, COL_OVER_BG)
  end
end

Log.info("ShooterApp.new")
begin
  app = ShooterApp.new
  app.start
rescue => e
  Log.error("Exception: #{e.class}")
  Log.error("Message: #{e.message}")
  Log.error(e.backtrace.join("\n")) if e.backtrace
end
