# Shooter - a formation shoot 'em up.
#
# Controls
#   Keyboard: arrows move, Space fires (hold to keep firing), Enter restarts
#   Gamepad:  D-pad / left stick move, Circle fires, Cross restarts, Start quits
#
# The artwork is a set of BMPs under /usr/share/sprites/shooter, the same
# route flappy.rb uses: the files are transferred to the graphics side once
# (sync_file, which skips the copy when the CRC already matches) and decoded
# there by SpriteImage#load_bmp. The editable source is the pixel art in
# tool/gen_shooter_sprites.rb -- edit it there and re-run "rake sprites".
#
# Enemies arrive as a block: each one flies in from off screen along an arc,
# settles into its slot, sways with the rest of the formation, and now and
# then one peels off to dive at the player. Clearing the block does not start
# the next wave straight away -- first a boss drops in.
#
# The boss is the same enemy drawing blown up five times (boss_a/boss_b, 80x60,
# written by the same generator at scale 5) in a palette of its own. It slides
# across the top out of the player's reach and shoots back: a three-way spread,
# and every third volley a shot aimed at where the ship is. It takes many hits,
# and the HUD carries a bar for what is left of it. Only when it is destroyed
# does the next wave stream in, so a wave now reads as block -> boss -> block.
#
# Sound is the APU (FmrbAudio#note_on / #note_off): a falling pulse blip when
# the player fires, a noise burst when something is hit, and a longer low
# noise plus a triangle thud when the player is hit. Every effect is started
# with note_on and finished by tick_sfx counting down to note_off, which is
# the pattern rpg_demo uses; @sfx_seq stops a finished effect from silencing
# the one that replaced it on the same channel. The boss brings three more:
# an alarm as it arrives, a duller blip than the player's for its own shots,
# and a long noise sweep as it comes apart.

class ShooterApp < FmrbApp
  # ---- Palette (RGB332) ----
  COL_HUD_BG   = 0x00
  COL_HUD_LINE = 0x49
  COL_TEXT     = 0xFF
  COL_SKY      = 0x00
  COL_STAR_HI  = 0xFF
  COL_STAR_MID = 0xB6
  COL_STAR_LO  = 0x49
  COL_PLANET   = 0x21
  COL_PLANET_R = 0x4A
  # The glow along the horizon. The same blue-violet as the planet's lit rim,
  # so the line reads as that light reaching the horizon -- as pure green it
  # read as a stray bar across the bottom of the screen.
  COL_HORIZON  = 0x4A
  COL_OVER_BG  = 0x40
  COL_BOSS_HP    = 0xE0
  COL_BOSS_HP_BG = 0x24

  # ---- Artwork ----
  # Generated by tool/gen_shooter_sprites.rb. The two enemy types and the boss
  # are the same drawing in three palettes (the boss also at five times the
  # size), so the colour is already baked into the file.
  SPRITE_SRC = "/usr/share/sprites/shooter"
  SPRITE_CACHE = "/cache/app/shooter"
  SPRITE_FILES = ["player_a.bmp", "player_b.bmp",
                  "enemy1_a.bmp", "enemy1_b.bmp",
                  "enemy2_a.bmp", "enemy2_b.bmp",
                  "boss_a.bmp", "boss_b.bmp",
                  "bullet.bmp", "ebullet.bmp",
                  "burst_a.bmp", "burst_b.bmp"]

  PLAYER_W = 16
  PLAYER_H = 16
  ENEMY_W  = 16
  ENEMY_H  = 12
  BULLET_W = 4
  BULLET_H = 6
  BURST_W  = 16
  BURST_H  = 16
  # The enemy art at BOSS_SCALE. Kept as plain numbers because every hit test
  # and every placement uses them; the scale is only here to say where they
  # came from.
  BOSS_SCALE = 5
  BOSS_W   = ENEMY_W * BOSS_SCALE
  BOSS_H   = ENEMY_H * BOSS_SCALE
  EBULLET_W = 4
  EBULLET_H = 6

  # ---- Layout ----
  HUD_H = 12
  FORM_COLS = 6
  FORM_ROWS = 3
  CELL_W = 28
  CELL_H = 22
  FORM_TOP = HUD_H + 16
  SWAY_MAX = 12
  SWAY_EVERY = 3          # ticks between one pixel of formation drift

  # ---- Play ----
  MAX_BULLETS = 6
  MAX_BURSTS  = 4
  PLAYER_SPEED = 4
  BULLET_SPEED = 9
  SHOT_COOLDOWN = 4       # ticks between shots while the fire key is held
  ENTER_TICKS = 26        # length of the fly-in path
  DIVE_TURN = 18          # ticks a diver takes to line up with the player
  DIVE_SPEED = 5
  INVULN_TICKS = 30
  START_LIVES = 3
  TICK_MS = 50

  # ---- Boss ----
  MAX_EBULLETS = 12
  BOSS_TOP = HUD_H + 6        # where it settles, well above the player's range
  BOSS_ENTER_TICKS = 30
  BOSS_DIE_TICKS = 40
  BOSS_HP_BASE = 24
  BOSS_HP_PER_WAVE = 8
  BOSS_FIRE_EVERY = 22        # before the per-wave speed-up
  EBULLET_SPEED = 5
  BOSS_BAR_W = 90

  # Quarter of a sine, scaled to 127. Used for the fly-in arc and the wiggle
  # of a diving enemy; a table keeps the paths curved without floating point.
  SIN16 = [0, 49, 90, 118, 127, 118, 90, 49,
           0, -49, -90, -118, -127, -118, -90, -49]

  # ---- APU ----
  CH_PULSE1 = 0
  CH_PULSE2 = 1
  CH_TRI    = 2
  CH_NOISE  = 3

  def initialize
    super()
    @input = {}
    @fire_held = false
    @restart_pressed = false
  end

  def on_create
    Log.info("Shooter on_create")
    FmrbApp.set_cursor_visible(false)
    @play_h = @user_area_height
    setup_audio
    setup_sprites
    reset_game
  end

  def on_destroy
    silence_audio
    destroy_sprites
    FmrbApp.set_cursor_visible(true)
    Log.info("Shooter destroyed")
  end

  # ---- Setup -----------------------------------------------------------

  def setup_audio
    # picoruby has no defined?, so just try it: the rescue covers both a
    # missing FmrbAudio and an audio side that will not start.
    @audio = FmrbAudio.new(self)
    @sfx_seq = [0, 0, 0, 0]
    @sfx_pending = []
  rescue => e
    Log.warn("Audio unavailable: #{e.message}")
    @audio = nil
    @sfx_seq = [0, 0, 0, 0]
    @sfx_pending = []
  end

  # Show progress while the files go across: on a cold cache this is twelve
  # transfers -- two of them the 80x60 boss frames -- and the screen would
  # otherwise sit blank.
  def transfer_sprites
    ox = @user_area_x0
    oy = @user_area_y0
    i = 0
    while i < SPRITE_FILES.length
      name = SPRITE_FILES[i]
      @gfx.fill_rect(ox, oy, @user_area_width, @play_h, COL_SKY)
      @gfx.draw_text(ox + 8, oy + 10, "Loading sprites...", COL_TEXT, COL_SKY)
      @gfx.draw_text(ox + 8, oy + 24,
                     "#{name} (#{i + 1}/#{SPRITE_FILES.length})", 0x1F, COL_SKY)
      @gfx.present
      @gfx.sync_file("#{SPRITE_SRC}/#{name}", dest: "#{SPRITE_CACHE}/#{name}")
      i += 1
    end
    Log.info("Shooter: sprites transferred")
  end

  def load_sprite_image(name, w, h)
    img = SpriteImage.new(@gfx, width: w, height: h,
                          transparent_color: 0, use_transparent: true)
    img.load_bmp("#{SPRITE_CACHE}/#{name}")
    img
  end

  def setup_sprites
    transfer_sprites
    @player_imgs = [load_sprite_image("player_a.bmp", PLAYER_W, PLAYER_H),
                    load_sprite_image("player_b.bmp", PLAYER_W, PLAYER_H)]
    @enemy_imgs = [
      [load_sprite_image("enemy1_a.bmp", ENEMY_W, ENEMY_H),
       load_sprite_image("enemy1_b.bmp", ENEMY_W, ENEMY_H)],
      [load_sprite_image("enemy2_a.bmp", ENEMY_W, ENEMY_H),
       load_sprite_image("enemy2_b.bmp", ENEMY_W, ENEMY_H)],
    ]
    @boss_imgs = [load_sprite_image("boss_a.bmp", BOSS_W, BOSS_H),
                  load_sprite_image("boss_b.bmp", BOSS_W, BOSS_H)]
    @bullet_img = load_sprite_image("bullet.bmp", BULLET_W, BULLET_H)
    @ebullet_img = load_sprite_image("ebullet.bmp", EBULLET_W, EBULLET_H)
    @burst_imgs = [load_sprite_image("burst_a.bmp", BURST_W, BURST_H),
                   load_sprite_image("burst_b.bmp", BURST_W, BURST_H)]

    @player_sprite = SpriteInstance.new(@gfx, @player_imgs, x: 0, y: 0, z: 3)
    @player_sprite.visible = false

    @bullet_pool = []
    i = 0
    while i < MAX_BULLETS
      s = SpriteInstance.new(@gfx, @bullet_img, x: 0, y: 0, z: 2)
      s.visible = false
      @bullet_pool << s
      i += 1
    end

    # One instance per formation slot: the block never holds more than that,
    # so the pool never has to grow or shuffle.
    @enemy_sprites = []
    i = 0
    while i < FORM_COLS * FORM_ROWS
      row = i / FORM_COLS
      s = SpriteInstance.new(@gfx, @enemy_imgs[row == 0 ? 1 : 0], x: 0, y: 0, z: 2)
      s.visible = false
      @enemy_sprites << s
      i += 1
    end

    @ebullet_pool = []
    i = 0
    while i < MAX_EBULLETS
      s = SpriteInstance.new(@gfx, @ebullet_img, x: 0, y: 0, z: 2)
      s.visible = false
      @ebullet_pool << s
      i += 1
    end

    # Behind the bullets, so a shot crossing the boss still reads as a shot.
    @boss_sprite = SpriteInstance.new(@gfx, @boss_imgs, x: 0, y: 0, z: 1)
    @boss_sprite.visible = false

    @burst_pool = []
    i = 0
    while i < MAX_BURSTS
      s = SpriteInstance.new(@gfx, @burst_imgs, x: 0, y: 0, z: 4)
      s.visible = false
      @burst_pool << s
      i += 1
    end
  end

  def destroy_sprites
    @bullet_pool.each { |s| s.destroy } if @bullet_pool
    @ebullet_pool.each { |s| s.destroy } if @ebullet_pool
    @enemy_sprites.each { |s| s.destroy } if @enemy_sprites
    @burst_pool.each { |s| s.destroy } if @burst_pool
    @boss_sprite.destroy if @boss_sprite
    @player_sprite.destroy if @player_sprite
    @player_imgs.each { |i| i.destroy } if @player_imgs
    @enemy_imgs.each { |pair| pair.each { |i| i.destroy } } if @enemy_imgs
    @boss_imgs.each { |i| i.destroy } if @boss_imgs
    @burst_imgs.each { |i| i.destroy } if @burst_imgs
    @bullet_img.destroy if @bullet_img
    @ebullet_img.destroy if @ebullet_img
  end

  # ---- Game state ------------------------------------------------------

  def reset_game
    @score = 0
    @lives = START_LIVES
    @wave = 1
    @game_over = false
    @tick = 0
    @sway = 0
    @sway_dir = 1
    @invuln = 0
    @shot_timer = 0
    @dive_timer = 60
    @bullets = []
    @ebullets = []
    @bursts = []
    @free_bullets = @bullet_pool.dup
    @free_ebullets = @ebullet_pool.dup
    @free_bursts = @burst_pool.dup
    @input = {}
    @fire_held = false
    @phase = :wave
    @boss = nil
    @boss_frame = -1
    @boss_sprite.visible = false

    @player_x = @user_area_width / 2
    @player_y = @play_h - PLAYER_H - 10

    start_wave
    draw_background
    draw_hud
    @player_sprite.visible = true
    move_player_sprite
    @gfx.present
  end

  def start_wave
    @enemies = []
    idx = 0
    while idx < FORM_COLS * FORM_ROWS
      col = idx % FORM_COLS
      row = idx / FORM_COLS
      sprite = @enemy_sprites[idx]
      sprite.visible = true
      # Odd columns come in from the right, even ones from the left, and each
      # one waits a little longer than the last so the block streams in.
      from_left = (col % 2) == 0
      e = {
        sprite: sprite, col: col, row: row,
        state: :enter, t: -(col * 3 + row * 5),
        sx: from_left ? -ENEMY_W - 8 : @user_area_width + 8,
        sy: HUD_H + 4 + row * 6,
        x: 0, y: -40, tx: 0, dive_x: 0, dive_y: 0,
      }
      # Park it off screen straight away: the sprite is visible from here on,
      # and without this it would show at its position from the last wave
      # until the first update moved it.
      sprite.move(@user_area_x0 + e[:x], @user_area_y0 + e[:y])
      @enemies << e
      idx += 1
    end
    @dive_timer = 70
  end

  # ---- Input -----------------------------------------------------------

  def on_event(ev)
    super(ev)
    case ev[:type]
    when :key_down
      # Arrow keys carry no character, so they come in as scancodes (HID
      # usage ids, which is what FmrbConst::KEY_* holds).
      case ev[:scancode]
      when FmrbConst::KEY_LEFT  then @input[:left]  = true
      when FmrbConst::KEY_RIGHT then @input[:right] = true
      when FmrbConst::KEY_UP    then @input[:up]    = true
      when FmrbConst::KEY_DOWN  then @input[:down]  = true
      end
      c = ev[:character]
      @fire_held = true if c == 32
      @restart_pressed = true if c == 10 || c == 13
    when :key_up
      case ev[:scancode]
      when FmrbConst::KEY_LEFT  then @input[:left]  = false
      when FmrbConst::KEY_RIGHT then @input[:right] = false
      when FmrbConst::KEY_UP    then @input[:up]    = false
      when FmrbConst::KEY_DOWN  then @input[:down]  = false
      end
      @fire_held = false if ev[:character] == 32
    when :gamepad_down
      case ev[:button]
      when FmrbConst::GP_UP     then @input[:up]    = true
      when FmrbConst::GP_DOWN   then @input[:down]  = true
      when FmrbConst::GP_LEFT   then @input[:left]  = true
      when FmrbConst::GP_RIGHT  then @input[:right] = true
      when FmrbConst::GP_CIRCLE then @fire_held = true
      when FmrbConst::GP_CROSS  then @restart_pressed = true
      when FmrbConst::GP_START  then stop
      end
    when :gamepad_up
      case ev[:button]
      when FmrbConst::GP_UP     then @input[:up]    = false
      when FmrbConst::GP_DOWN   then @input[:down]  = false
      when FmrbConst::GP_LEFT   then @input[:left]  = false
      when FmrbConst::GP_RIGHT  then @input[:right] = false
      when FmrbConst::GP_CIRCLE then @fire_held = false
      end
    when :gamepad_axis
      if ev[:axis] == FmrbConst::GP_AXIS_LX
        v = ev[:value]
        @input[:left]  = v < -30
        @input[:right] = v > 30
      elsif ev[:axis] == FmrbConst::GP_AXIS_LY
        v = ev[:value]
        @input[:up]   = v < -30
        @input[:down] = v > 30
      end
    end
  end

  # ---- Frame -----------------------------------------------------------

  def on_update
    if @game_over
      if @restart_pressed
        @restart_pressed = false
        reset_game
      end
      return TICK_MS
    end
    @restart_pressed = false
    @tick += 1

    update_player
    update_bullets
    if @phase == :boss
      update_boss
    else
      update_formation
      update_enemies
    end
    update_ebullets
    update_bursts
    check_hits
    tick_sfx
    return TICK_MS if @game_over

    # Clearing the block no longer starts the next wave: the boss comes first,
    # and end_boss is what moves the wave on.
    start_boss if @phase == :wave && @enemies.empty?

    @gfx.present
    TICK_MS
  end

  def update_player
    @player_x -= PLAYER_SPEED if @input[:left]
    @player_x += PLAYER_SPEED if @input[:right]
    @player_y -= PLAYER_SPEED if @input[:up]
    @player_y += PLAYER_SPEED if @input[:down]

    @player_x = 0 if @player_x < 0
    max_x = @user_area_width - PLAYER_W
    @player_x = max_x if @player_x > max_x
    # Kept below the block: only divers are checked against the player, so
    # letting the ship wander up into the formation would look wrong.
    min_y = FORM_TOP + FORM_ROWS * CELL_H + 16
    @player_y = min_y if @player_y < min_y
    max_y = @play_h - PLAYER_H
    @player_y = max_y if @player_y > max_y

    # Exhaust flicker, and the blink that shows the player is still safe
    # after being hit.
    @player_sprite.frame = (@tick % 4 < 2) ? 0 : 1
    if @invuln > 0
      @invuln -= 1
      @player_sprite.visible = (@invuln % 4) < 2
      @player_sprite.visible = true if @invuln == 0
    end
    move_player_sprite

    @shot_timer -= 1 if @shot_timer > 0
    if @fire_held && @shot_timer == 0
      fire_bullet
      @shot_timer = SHOT_COOLDOWN
    end
  end

  def move_player_sprite
    @player_sprite.move(@user_area_x0 + @player_x, @user_area_y0 + @player_y)
  end

  def fire_bullet
    return if @free_bullets.empty?
    s = @free_bullets.pop
    x = @player_x + PLAYER_W / 2 - BULLET_W / 2
    y = @player_y - BULLET_H
    s.visible = true
    s.move(@user_area_x0 + x, @user_area_y0 + y)
    @bullets << { x: x, y: y, sprite: s }
    sfx_shot
  end

  def update_bullets
    i = @bullets.length - 1
    while i >= 0
      b = @bullets[i]
      b[:y] -= BULLET_SPEED
      if b[:y] < HUD_H - BULLET_H
        release_bullet(i)
      else
        b[:sprite].move(@user_area_x0 + b[:x], @user_area_y0 + b[:y])
      end
      i -= 1
    end
  end

  def release_bullet(i)
    b = @bullets[i]
    b[:sprite].visible = false
    @free_bullets.push(b[:sprite])
    @bullets.delete_at(i)
  end

  # The whole block drifts sideways together.
  def update_formation
    return unless (@tick % SWAY_EVERY) == 0
    @sway += @sway_dir
    if @sway >= SWAY_MAX
      @sway = SWAY_MAX
      @sway_dir = -1
    elsif @sway <= -SWAY_MAX
      @sway = -SWAY_MAX
      @sway_dir = 1
    end
  end

  def form_x0
    (@user_area_width - FORM_COLS * CELL_W) / 2 + (CELL_W - ENEMY_W) / 2
  end

  def slot_x(col); form_x0 + col * CELL_W + @sway; end
  def slot_y(row); FORM_TOP + row * CELL_H; end

  def update_enemies
    @dive_timer -= 1
    launch_dive if @dive_timer <= 0

    i = 0
    n = @enemies.length
    while i < n
      e = @enemies[i]
      case e[:state]
      when :enter then step_enter(e)
      when :form  then step_form(e)
      else             step_dive(e)
      end
      e[:sprite].move(@user_area_x0 + e[:x], @user_area_y0 + e[:y])
      i += 1
    end
    # Wing beat, shared by the whole block so it reads as one swarm.
    frame = (@tick % 8 < 4) ? 0 : 1
    if frame != @enemy_frame
      @enemy_frame = frame
      i = 0
      while i < n
        @enemies[i][:sprite].frame = frame
        i += 1
      end
    end
  end

  # Fly in from off screen to the slot, bulging along the way so the path is
  # an arc rather than a straight line.
  def step_enter(e)
    e[:t] += 1
    return if e[:t] < 0
    if e[:t] >= ENTER_TICKS
      e[:state] = :form
      step_form(e)
      return
    end
    tx = slot_x(e[:col])
    ty = slot_y(e[:row])
    p = e[:t]
    e[:x] = e[:sx] + (tx - e[:sx]) * p / ENTER_TICKS
    e[:y] = e[:sy] + (ty - e[:sy]) * p / ENTER_TICKS + SIN16[p * 8 / ENTER_TICKS] * 26 / 127
  end

  def step_form(e)
    e[:x] = slot_x(e[:col])
    e[:y] = slot_y(e[:row])
  end

  # Dive: swing toward where the player was, wiggling, then run off the
  # bottom and come back round to the slot.
  def step_dive(e)
    e[:t] += 1
    p = e[:t]
    turn = p < DIVE_TURN ? p : DIVE_TURN
    base = e[:dive_x] + (e[:tx] - e[:dive_x]) * turn / DIVE_TURN
    e[:x] = base + SIN16[p % 16] * 14 / 127
    e[:y] = e[:dive_y] + p * DIVE_SPEED
    if e[:y] > @play_h + ENEMY_H
      e[:state] = :enter
      e[:t] = 0
      e[:sx] = e[:x]
      e[:sy] = -ENEMY_H
    end
  end

  def launch_dive
    # Pick a settled enemy from the lowest row that still has one: the block
    # empties from the bottom, which is what makes it read as a formation.
    pick = nil
    i = @enemies.length - 1
    while i >= 0
      e = @enemies[i]
      if e[:state] == :form && (pick.nil? || e[:row] > pick[:row])
        pick = e
      end
      i -= 1
    end
    @dive_timer = 70 - @wave * 6
    @dive_timer = 18 if @dive_timer < 18
    return unless pick
    pick[:state] = :dive
    pick[:t] = 0
    pick[:dive_x] = pick[:x]
    pick[:dive_y] = pick[:y]
    pick[:tx] = @player_x
  end

  # ---- Boss ------------------------------------------------------------

  def start_boss
    @phase = :boss
    hp = BOSS_HP_BASE + (@wave - 1) * BOSS_HP_PER_WAVE
    x = (@user_area_width - BOSS_W) / 2
    @boss = { x: x, y: -BOSS_H, hp: hp, max_hp: hp,
              state: :enter, t: 0, dir: 1,
              fire: boss_fire_every, shot: 0, flash: 0 }
    @boss_frame = -1
    @boss_sprite.frame = 0
    @boss_sprite.visible = true
    @boss_sprite.move(@user_area_x0 + x, @user_area_y0 + @boss[:y])
    sfx_boss_alarm
    draw_hud
  end

  # Both scale with the wave, so a later boss is faster and fires more often
  # without needing a second pattern.
  def boss_speed
    s = 2 + @wave / 2
    s > 5 ? 5 : s
  end

  def boss_fire_every
    n = BOSS_FIRE_EVERY - @wave * 2
    n < 9 ? 9 : n
  end

  def update_boss
    b = @boss
    if b[:state] == :die
      step_boss_die(b)
      return
    end

    if b[:state] == :enter
      b[:t] += 1
      p = b[:t]
      p = BOSS_ENTER_TICKS if p > BOSS_ENTER_TICKS
      b[:y] = -BOSS_H + (BOSS_TOP + BOSS_H) * p / BOSS_ENTER_TICKS
      # The warning blinks, so the HUD has to be repainted while it drops in.
      draw_hud
      if b[:t] >= BOSS_ENTER_TICKS
        b[:state] = :fight
        b[:t] = 0
        draw_hud
      end
    else
      b[:t] += 1
      b[:x] += b[:dir] * boss_speed
      if b[:x] <= 0
        b[:x] = 0
        b[:dir] = 1
      elsif b[:x] >= @user_area_width - BOSS_W
        b[:x] = @user_area_width - BOSS_W
        b[:dir] = -1
      end
      # A slow bob on top of the slide, so it does not read as a sliding tile.
      b[:y] = BOSS_TOP + SIN16[(b[:t] / 3) % 16] * 5 / 127
      b[:fire] -= 1
      if b[:fire] <= 0
        boss_fire
        b[:fire] = boss_fire_every
      end
    end

    # Half the beat of the small ones: at this size a fast flap looks like a
    # glitch rather than like wings.
    frame = (@tick % 12 < 6) ? 0 : 1
    if frame != @boss_frame
      @boss_frame = frame
      @boss_sprite.frame = frame
    end
    if b[:flash] > 0
      b[:flash] -= 1
      @boss_sprite.visible = (b[:flash] % 2) == 0
    end
    @boss_sprite.move(@user_area_x0 + b[:x], @user_area_y0 + b[:y])
  end

  def boss_fire
    bx = @boss[:x] + BOSS_W / 2 - EBULLET_W / 2
    by = @boss[:y] + BOSS_H - 14
    if (@boss[:shot] % 3) == 2
      # Aimed: the sideways speed is whatever lines the shot up with the ship
      # by the time it has fallen that far.
      dx = (@player_x + PLAYER_W / 2) - (bx + EBULLET_W / 2)
      dy = @player_y - by
      dy = 1 if dy < 1
      vx = dx * EBULLET_SPEED / dy
      vx = 5 if vx > 5
      vx = -5 if vx < -5
      spawn_ebullet(bx, by, vx, EBULLET_SPEED)
    else
      spawn_ebullet(bx, by, 0, EBULLET_SPEED)
      spawn_ebullet(bx - 18, by - 6, -2, EBULLET_SPEED - 1)
      spawn_ebullet(bx + 18, by - 6, 2, EBULLET_SPEED - 1)
    end
    @boss[:shot] += 1
    sfx_boss_shot
  end

  def boss_damage(x, y)
    @boss[:hp] -= 1
    @boss[:flash] = 2
    @score += 25
    if @boss[:hp] <= 0
      boss_defeated
    else
      spawn_burst(x - BURST_W / 2, y - BURST_H / 2)
      sfx_hit
    end
    draw_hud
  end

  def boss_defeated
    @boss[:state] = :die
    @boss[:t] = 0
    @score += 1000 + @wave * 500
    clear_ebullets
    sfx_boss_die
  end

  # Comes apart over BOSS_DIE_TICKS: bursts walk across it while it flickers.
  def step_boss_die(b)
    b[:t] += 1
    if (b[:t] % 5) == 1
      spawn_burst(b[:x] + (RNG.random_int % (BOSS_W - BURST_W)),
                  b[:y] + (RNG.random_int % (BOSS_H - BURST_H)))
    end
    @boss_sprite.visible = (b[:t] % 4) < 2
    @boss_sprite.move(@user_area_x0 + b[:x], @user_area_y0 + b[:y])
    end_boss if b[:t] >= BOSS_DIE_TICKS
  end

  def end_boss
    @boss_sprite.visible = false
    @boss = nil
    @phase = :wave
    @wave += 1
    @score += 500
    sfx_wave
    start_wave
    draw_hud
  end

  # ---- Enemy fire ------------------------------------------------------

  def spawn_ebullet(x, y, vx, vy)
    return if @free_ebullets.empty?
    s = @free_ebullets.pop
    s.visible = true
    s.move(@user_area_x0 + x, @user_area_y0 + y)
    @ebullets << { x: x, y: y, vx: vx, vy: vy, sprite: s }
  end

  def update_ebullets
    i = @ebullets.length - 1
    while i >= 0
      b = @ebullets[i]
      b[:x] += b[:vx]
      b[:y] += b[:vy]
      if b[:y] > @play_h || b[:x] < -EBULLET_W || b[:x] > @user_area_width
        release_ebullet(i)
      else
        b[:sprite].move(@user_area_x0 + b[:x], @user_area_y0 + b[:y])
      end
      i -= 1
    end
  end

  def release_ebullet(i)
    b = @ebullets[i]
    b[:sprite].visible = false
    @free_ebullets.push(b[:sprite])
    @ebullets.delete_at(i)
  end

  # Wiping the screen of enemy fire: on respawn, and when the boss dies with
  # its last volley still falling.
  def clear_ebullets
    i = @ebullets.length - 1
    while i >= 0
      release_ebullet(i)
      i -= 1
    end
  end

  # ---- Hits ------------------------------------------------------------

  def check_hits
    bi = @bullets.length - 1
    while bi >= 0
      b = @bullets[bi]
      # The box is pulled in from the sheet: the drawing's wing tips and legs
      # are thin, and at five times the size a hit on the empty corner would
      # be very visible.
      if @boss && @boss[:state] == :fight &&
         overlap?(b[:x], b[:y], BULLET_W, BULLET_H,
                  @boss[:x] + 10, @boss[:y] + 5, BOSS_W - 20, BOSS_H - 20)
        boss_damage(b[:x], b[:y])
        release_bullet(bi)
      else
        ei = @enemies.length - 1
        hit = -1
        while ei >= 0
          e = @enemies[ei]
          if e[:state] != :enter || e[:t] >= 0
            if overlap?(b[:x], b[:y], BULLET_W, BULLET_H,
                        e[:x], e[:y], ENEMY_W, ENEMY_H)
              hit = ei
              break
            end
          end
          ei -= 1
        end
        if hit >= 0
          e = @enemies[hit]
          spawn_burst(e[:x], e[:y] - 2)
          e[:sprite].visible = false
          @enemies.delete_at(hit)
          release_bullet(bi)
          @score += (e[:state] == :dive) ? 200 : 100
          sfx_hit
          draw_hud
        end
      end
      bi -= 1
    end

    return if @invuln > 0
    i = 0
    n = @enemies.length
    while i < n
      e = @enemies[i]
      if e[:state] == :dive &&
         overlap?(@player_x + 2, @player_y + 2, PLAYER_W - 4, PLAYER_H - 4,
                  e[:x] + 2, e[:y] + 2, ENEMY_W - 4, ENEMY_H - 4)
        player_hit
        return
      end
      i += 1
    end

    i = @ebullets.length - 1
    while i >= 0
      b = @ebullets[i]
      if overlap?(@player_x + 3, @player_y + 3, PLAYER_W - 6, PLAYER_H - 6,
                  b[:x], b[:y], EBULLET_W, EBULLET_H)
        release_ebullet(i)
        player_hit
        return
      end
      i -= 1
    end
  end

  def overlap?(x1, y1, w1, h1, x2, y2, w2, h2)
    !(x1 + w1 <= x2 || x2 + w2 <= x1 || y1 + h1 <= y2 || y2 + h2 <= y1)
  end

  def player_hit
    spawn_burst(@player_x, @player_y)
    sfx_player_hit
    @lives -= 1
    if @lives <= 0
      trigger_game_over
      return
    end
    @invuln = INVULN_TICKS
    @player_x = @user_area_width / 2
    @player_y = @play_h - PLAYER_H - 10
    # Nothing the boss already fired should still be in the air over the
    # respawn: the ship is put back in the middle, where the spread lands.
    clear_ebullets
    # Send the divers home rather than leaving them on top of the respawn.
    i = 0
    n = @enemies.length
    while i < n
      e = @enemies[i]
      if e[:state] == :dive
        e[:state] = :enter
        e[:t] = 0
        e[:sx] = e[:x]
        e[:sy] = e[:y]
      end
      i += 1
    end
    draw_hud
  end

  def spawn_burst(x, y)
    return if @free_bursts.empty?
    s = @free_bursts.pop
    s.frame = 0
    s.visible = true
    s.move(@user_area_x0 + x, @user_area_y0 + y)
    @bursts << { sprite: s, t: 0 }
  end

  def update_bursts
    i = @bursts.length - 1
    while i >= 0
      b = @bursts[i]
      b[:t] += 1
      if b[:t] >= 6
        b[:sprite].visible = false
        @free_bursts.push(b[:sprite])
        @bursts.delete_at(i)
      elsif b[:t] == 3
        b[:sprite].frame = 1
      end
      i -= 1
    end
  end

  def trigger_game_over
    @game_over = true
    @player_sprite.visible = false
    i = 0
    while i < @enemies.length
      @enemies[i][:sprite].visible = false
      i += 1
    end
    @boss_sprite.visible = false
    @boss = nil
    @phase = :wave
    @bullets.each { |b| b[:sprite].visible = false }
    @ebullets.each { |b| b[:sprite].visible = false }
    @bursts.each { |b| b[:sprite].visible = false }
    @bullets = []
    @ebullets = []
    @bursts = []
    @free_bullets = @bullet_pool.dup
    @free_ebullets = @ebullet_pool.dup
    @free_bursts = @burst_pool.dup
    silence_audio
    draw_hud
    draw_game_over
    @gfx.present
  end

  # ---- Sound -----------------------------------------------------------

  # Each effect claims its channel with a new sequence number, so the
  # note_off queued by the previous effect cannot cut this one short.
  def sfx_begin(ch)
    @sfx_seq[ch] = @sfx_seq[ch] + 1
    @sfx_seq[ch]
  end

  def sfx_shot
    return unless @audio
    g = sfx_begin(CH_PULSE2)
    @audio.note_on(CH_PULSE2, 1500, 5, 2, 0)
    @sfx_pending << { ch: CH_PULSE2, gen: g, t: 1, freq: 950, vol: 4, duty: 2 }
    @sfx_pending << { ch: CH_PULSE2, gen: g, t: 2, freq: nil }
  end

  def sfx_hit
    return unless @audio
    g = sfx_begin(CH_NOISE)
    @audio.note_on(CH_NOISE, 5, 10, 0, 0)
    @sfx_pending << { ch: CH_NOISE, gen: g, t: 1, freq: 8, vol: 7, duty: 0 }
    @sfx_pending << { ch: CH_NOISE, gen: g, t: 3, freq: nil }
  end

  def sfx_player_hit
    return unless @audio
    g = sfx_begin(CH_NOISE)
    @audio.note_on(CH_NOISE, 11, 13, 0, 0)
    @sfx_pending << { ch: CH_NOISE, gen: g, t: 3, freq: 14, vol: 9, duty: 0 }
    @sfx_pending << { ch: CH_NOISE, gen: g, t: 8, freq: nil }
    gt = sfx_begin(CH_TRI)
    @audio.note_on(CH_TRI, 100, 0, 0, 0)
    @sfx_pending << { ch: CH_TRI, gen: gt, t: 8, freq: nil }
  end

  def sfx_wave
    return unless @audio
    g = sfx_begin(CH_PULSE1)
    @audio.note_on(CH_PULSE1, 660, 6, 2, 0)
    @sfx_pending << { ch: CH_PULSE1, gen: g, t: 3, freq: 880, vol: 6, duty: 2 }
    @sfx_pending << { ch: CH_PULSE1, gen: g, t: 6, freq: 1320, vol: 6, duty: 2 }
    @sfx_pending << { ch: CH_PULSE1, gen: g, t: 10, freq: nil }
  end

  # Two low blasts as it drops in. On CH_PULSE1, which otherwise only carries
  # the wave fanfare, so nothing the player is doing gets cut off.
  def sfx_boss_alarm
    return unless @audio
    g = sfx_begin(CH_PULSE1)
    @audio.note_on(CH_PULSE1, 200, 8, 1, 0)
    @sfx_pending << { ch: CH_PULSE1, gen: g, t: 4, freq: 150, vol: 8, duty: 1 }
    @sfx_pending << { ch: CH_PULSE1, gen: g, t: 8, freq: 200, vol: 8, duty: 1 }
    @sfx_pending << { ch: CH_PULSE1, gen: g, t: 12, freq: 150, vol: 8, duty: 1 }
    @sfx_pending << { ch: CH_PULSE1, gen: g, t: 16, freq: nil }
  end

  # Deliberately lower and duller than sfx_shot, so the two are told apart
  # while both are going off.
  def sfx_boss_shot
    return unless @audio
    g = sfx_begin(CH_PULSE1)
    @audio.note_on(CH_PULSE1, 320, 5, 1, 0)
    @sfx_pending << { ch: CH_PULSE1, gen: g, t: 1, freq: 210, vol: 4, duty: 1 }
    @sfx_pending << { ch: CH_PULSE1, gen: g, t: 3, freq: nil }
  end

  def sfx_boss_die
    return unless @audio
    g = sfx_begin(CH_NOISE)
    @audio.note_on(CH_NOISE, 13, 13, 0, 0)
    @sfx_pending << { ch: CH_NOISE, gen: g, t: 6, freq: 10, vol: 12, duty: 0 }
    @sfx_pending << { ch: CH_NOISE, gen: g, t: 14, freq: 6, vol: 9, duty: 0 }
    @sfx_pending << { ch: CH_NOISE, gen: g, t: 24, freq: nil }
    gt = sfx_begin(CH_TRI)
    @audio.note_on(CH_TRI, 160, 0, 0, 0)
    @sfx_pending << { ch: CH_TRI, gen: gt, t: 10, freq: 90, vol: 0, duty: 0 }
    @sfx_pending << { ch: CH_TRI, gen: gt, t: 24, freq: nil }
  end

  def tick_sfx
    return unless @audio
    i = @sfx_pending.length - 1
    while i >= 0
      e = @sfx_pending[i]
      e[:t] -= 1
      if e[:t] <= 0
        if @sfx_seq[e[:ch]] == e[:gen]
          if e[:freq]
            @audio.note_on(e[:ch], e[:freq], e[:vol], e[:duty], 0)
          else
            @audio.note_off(e[:ch])
          end
        end
        @sfx_pending.delete_at(i)
      end
      i -= 1
    end
  end

  def silence_audio
    return unless @audio
    ch = 0
    while ch < 4
      @audio.note_off(ch)
      ch += 1
    end
    @sfx_pending = []
  end

  # ---- Drawing ---------------------------------------------------------

  # Drawn once per game: the sprites are composited over it on every present,
  # so nothing here is repainted per frame.
  def draw_background
    ox = @user_area_x0
    oy = @user_area_y0
    w = @user_area_width
    h = @play_h
    @gfx.fill_rect(ox, oy, w, h, COL_SKY)

    i = 0
    while i < 90
      sx = ox + (RNG.random_int % w)
      sy = oy + HUD_H + (RNG.random_int % (h - HUD_H))
      r = RNG.random_int % 10
      color = r < 2 ? COL_STAR_HI : (r < 5 ? COL_STAR_MID : COL_STAR_LO)
      @gfx.set_pixel(sx, sy, color)
      i += 1
    end

    # A planet rising at the bottom left, and the glow along the horizon.
    cx = ox + w / 5
    cy = oy + h + 46
    @gfx.fill_circle(cx, cy, 78, COL_PLANET)
    @gfx.draw_circle(cx, cy, 78, COL_PLANET_R)
    @gfx.fill_rect(ox, oy + h - 2, w, 2, COL_HORIZON)

    draw_window_frame
  end

  def draw_hud
    ox = @user_area_x0
    oy = @user_area_y0
    w = @user_area_width
    @gfx.fill_rect(ox, oy, w, HUD_H, COL_HUD_BG)
    @gfx.fill_rect(ox, oy + HUD_H - 1, w, 1, COL_HUD_LINE)
    @gfx.draw_text(ox + 2, oy + 2, sprintf("SCORE %06d", @score), COL_TEXT, COL_HUD_BG)
    if @boss
      draw_boss_hud(ox, oy, w)
    else
      @gfx.draw_text(ox + w / 2 - 18, oy + 2, sprintf("WAVE %02d", @wave), COL_TEXT, COL_HUD_BG)
    end
    # Lives as little ships rather than a number.
    lx = ox + w - 8
    i = 0
    while i < @lives - 1
      @gfx.fill_triangle(lx, oy + 3, lx - 4, oy + 9, lx + 4, oy + 9, 0x1F)
      lx -= 11
      i += 1
    end
  end

  # The boss takes the middle of the HUD off the wave counter: a blinking
  # warning while it drops in, then a bar for what is left of it. There is no
  # room for either over the play area itself -- the background is painted once
  # and the sprites are composited over it, so anything drawn there would have
  # to be erased by repainting the stars.
  def draw_boss_hud(ox, oy, w)
    cx = ox + w / 2
    if @boss[:state] == :enter
      return if (@tick % 8) < 4
      # Not centred: while it drops in the boss is exactly there, and the
      # sprite is composited over the HUD, so a centred warning is covered by
      # the thing it is warning about. This sits in the gap between the boss
      # (the middle BOSS_W of the screen) and the lives, on both widths.
      @gfx.draw_text(ox + w - 110, oy + 2, "WARNING", COL_BOSS_HP, COL_HUD_BG)
      return
    end
    x = cx - BOSS_BAR_W / 2
    @gfx.fill_rect(x, oy + 3, BOSS_BAR_W, 6, COL_BOSS_HP_BG)
    hp = @boss[:hp]
    hp = 0 if hp < 0
    fill = BOSS_BAR_W * hp / @boss[:max_hp]
    @gfx.fill_rect(x, oy + 3, fill, 6, COL_BOSS_HP) if fill > 0
  end

  def draw_game_over
    ox = @user_area_x0
    oy = @user_area_y0
    cx = ox + @user_area_width / 2
    cy = oy + @play_h / 2
    @gfx.fill_rect(cx - 62, cy - 22, 124, 46, COL_OVER_BG)
    @gfx.fill_rect(cx - 62, cy - 22, 124, 1, COL_TEXT)
    @gfx.fill_rect(cx - 62, cy + 23, 124, 1, COL_TEXT)
    @gfx.draw_text(cx - 27, cy - 15, "GAME OVER", COL_TEXT, COL_OVER_BG)
    @gfx.draw_text(cx - 45, cy - 1, sprintf("SCORE %06d", @score), COL_TEXT, COL_OVER_BG)
    @gfx.draw_text(cx - 57, cy + 13, "ENTER retry  Ctrl-Q quit", COL_TEXT, COL_OVER_BG)
  end
end

Log.info("ShooterApp.new")
begin
  app = ShooterApp.new
  app.start
rescue => e
  Log.error("Exception: #{e.class}")
  Log.error("Message: #{e.message}")
  Log.error(e.backtrace.join("\n")) if e.backtrace
end
